#!/bin/bash
# This script is used to run an e2e test in CI (see config.yml and cond_run_script).
# It sets a few environment variables used inside the docker-compose.yml, pulls images, and runs docker-compose.
set -exu

export TEST=$1
export COMPOSE_FILE=${2:-./scripts/docker-compose.yml}

function docker_login() {
  # Retries up to 3 times with 10 second intervals
  for i in $(seq 1 3); do
    aws ecr get-login-password --region us-east-2 \
      | docker login --username AWS --password-stdin 278380418400.dkr.ecr.us-east-2.amazonaws.com \
      && return || sleep 10
  done
  echo "$@ failed docker_login after 3 attempts"
  exit 1
}

# Login to dockerhub.
docker_login

export PATH="$PATH:$(git rev-parse --show-toplevel)/build-system/scripts"

for REPO in aztec.js end-to-end aztec-sandbox; do
  retry docker pull $(calculate_image_uri $REPO)
  retry docker tag $(calculate_image_uri $REPO) aztecprotocol/$REPO:latest
done

docker-compose -f $COMPOSE_FILE rm -f
docker-compose -f $COMPOSE_FILE up --exit-code-from end-to-end
