#!/bin/bash
# This script is used to run an e2e test in CI (see config.yml and cond_spot_run_tests).
# It sets a few environment variables used inside the docker-compose.yml, pulls images, and runs docker-compose.
set -e

export TEST=$1
export COMPOSE_FILE=${2:-docker-compose.yml}

if [ -n "$COMMIT_HASH" ]; then
  $(aws ecr get-login --region us-east-2 --no-include-email) 2> /dev/null

  for REPO in aztec.js end-to-end aztec-sandbox; do
    docker pull 278380418400.dkr.ecr.us-east-2.amazonaws.com/$REPO:cache-$COMMIT_HASH
    docker tag 278380418400.dkr.ecr.us-east-2.amazonaws.com/$REPO:cache-$COMMIT_HASH aztecprotocol/$REPO:latest
  done
fi

docker-compose rm -f
docker-compose -f $COMPOSE_FILE up --exit-code-from end-to-end