#!/bin/bash
# This script is used to run an e2e test in CI (see config.yml and cond_spot_run_tests).
# It sets a few environment variables used inside the docker-compose.yml, pulls images, and runs docker-compose.
set -exu

export TEST=$1
export COMPOSE_FILE=${2:-docker-compose.yml}

$(aws ecr get-login --region us-east-2 --no-include-email) 2> /dev/null

export PATH="$PATH:$(git rev-parse --show-toplevel)/build-system/scripts"

for REPO in aztec.js end-to-end aztec-sandbox; do
  retry docker pull $($calculate_image_uri $REPO)
  retry docker tag $($calculate_image_uri $REPO) aztecprotocol/$REPO:latest
done

docker-compose rm -f
docker-compose -f $COMPOSE_FILE up --exit-code-from end-to-end
