#!/bin/bash
# This script is used to run an e2e test in CI (see config.yml and cond_run_script).
# It sets a few environment variables used inside the docker-compose.yml, pulls images, and runs docker-compose.
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

export TEST=$1
export COMPOSE_FILE=${2:-./scripts/docker-compose.yml}

# Login to ECR.
ecr_login

export PATH="$PATH:$(git rev-parse --show-toplevel)/build-system/scripts"

for REPO in end-to-end aztec-sandbox; do
  retry docker pull $(calculate_image_uri $REPO)
  retry docker tag $(calculate_image_uri $REPO) aztecprotocol/$REPO:latest
done

docker-compose -f $COMPOSE_FILE rm -f
docker-compose -f $COMPOSE_FILE up --exit-code-from end-to-end
