VERSION 0.8
IMPORT ../noir AS noir

source:
  # we rely on noir source, which this image has
  FROM noir+nargo

  # move noir contents to /usr/src/noir
  RUN mv /usr/src /noir && mkdir /usr/src && mv /noir /usr/src
  # work in avm-transpiler
  WORKDIR /usr/src/avm-transpiler

  COPY --dir scripts src Cargo.lock Cargo.toml rust-toolchain.toml .

build:
    FROM +source
    # build avm transpiler, and make sure the big build and deps folders don't hit cache
    RUN ./scripts/bootstrap_native.sh && rm -rf target/release/{build,deps}
    SAVE ARTIFACT target/release/avm-transpiler avm-transpiler

run:
    #TODO needed?
    FROM ubuntu:focal
    COPY +build/avm-transpiler /usr/src/avm-transpiler
    ENTRYPOINT ["sh", "-c"]
