VERSION 0.8
IMPORT ../noir AS noir
# we rely on noir source, which this image has
FROM noir+nargo

# move noir contents to /usr/src/noir
RUN mv /usr/src /noir && mkdir /usr/src && mv /noir /usr/src
# work in avm-transpiler
WORKDIR /usr/src/avm-transpiler

RUN apt-get update && apt-get install -y git

COPY --dir scripts src Cargo.lock Cargo.toml rust-toolchain.toml .

source:
  # for debugging rebuilds
  RUN echo CONTENT HASH $(find . -type f -exec sha256sum {} ';' | sort | sha256sum | awk '{print $1}') | tee .content-hash

build:
    FROM +source
    RUN ./scripts/bootstrap_native.sh
    SAVE ARTIFACT target/release/avm-transpiler avm-transpiler

run: 
    #TODO needed?
    FROM ubuntu:focal
    COPY +build/avm-transpiler /usr/src/avm-transpiler
    ENTRYPOINT ["sh", "-c"]
