/-
REVIEWED: this file is part of the trusted specification (`AcirLean/Spec/`).
Every definition here is taken on trust: read it against its comment. A change
to this directory needs careful review.
-/

/-!
# Which test programs the claims cover

The test-program data in `AcirLean/Templates/TestPrograms.lean` is generated,
and nobody reviews it. This list is what fixes its contents: `AllClaims`
requires the generated programs to be exactly these, in this order, so a
program can only leave the claims through a reviewed change to this file.
`scripts/gen_programs.py` reads it to decide which programs to rebuild, and
fails if one of them cannot be.
-/

namespace AcirLean

/-- The programs from `test_programs/execution_success` in `testPrograms`, by
name, sorted. Every one except `uncoveredPrograms` is claimed. -/
def testProgramNames : List String :=
  ["a_1327_concrete_in_generic",
   "a_1_mul",
   "a_2_div",
   "a_3_add",
   "a_4_sub",
   "a_5_over",
   "a_6_array",
   "arithmetic_binary_operations",
   "array_eq",
   "array_if_cond_simple",
   "array_of_references_in_loop",
   "as_str_unchecked_with_broken_bytes",
   "assert",
   "assert_statement",
   "assign_ex",
   "associated_constant_as_array_length",
   "bit_not",
   "bit_shifts_comptime",
   "bool_not",
   "brillig_block_mutable_reference_index_regression",
   "brillig_entry_points_regression_8069",
   "brillig_mutable_reference_lsf_bug",
   "cast_bool",
   "cast_regression_7776",
   "cast_signed_to_u1",
   "cast_to_u128",
   "chained_associated_type_in_signature",
   "closures_mut_ref",
   "comptime_closure_bindings_1",
   "comptime_closure_bindings_2",
   "comptime_function_definition_attribute_arg",
   "comptime_generics_binding",
   "comptime_mutated_global",
   "comptime_named_attribute_args",
   "comptime_println_fmtstr_with_quoted",
   "comptime_quoted_hash",
   "comptime_resolve_associated_constant_scope",
   "comptime_trait_constraint_hash_and_eq",
   "conditional_regression_547",
   "custom_entry",
   "debug_name_no_conflict",
   "defunctionalize_mut_ref_to_immut_ref_regression",
   "dereference_assignment",
   "diamond_deps_0",
   "division_by_max",
   "dont_deduplicate_call",
   "double_neg_cond_global_var",
   "dual_constrained_lambdas",
   "encrypted_log_regression",
   "field_attribute",
   "fn_value_callee_reads_then_repoints_ref_param_hint",
   "fn_value_callee_repoints_caller_ref_hint",
   "for_loop_inclusive_u8_max",
   "for_loop_signed_index_crosses_zero",
   "generics",
   "global_array_rc_regression_8259",
   "global_consts",
   "global_string_control_char",
   "higher_order_functions",
   "inline_decompose_hint_brillig_call",
   "inline_never_basic",
   "integer_array_indexing",
   "lambda_env_is_copied",
   "lambda_from_global_tuple",
   "large_nested_array_multi_field_merge",
   "local_module_does_not_conflict_with_debugger",
   "loop",
   "loop_carried_aliases",
   "main_bool_arg",
   "main_return",
   "match_struct_pattern_field_order",
   "missing_closure_env",
   "modules",
   "modules_more",
   "modulus",
   "negated_jmpif_condition",
   "nested_array_dynamic_simple",
   "nested_array_with_refs",
   "nested_vector_pop_back",
   "no_predicates_basic",
   "numeric_type_alias_inference",
   "numeric_type_alias_use_site_names",
   "op_assign_desugaring",
   "operator_overload_in_global",
   "overlapping_dep_and_mod",
   "pred_eq",
   "private_inherent_method_resolves_to_trait",
   "ref_in_struct_in_array_write_through_call",
   "ref_to_ref_in_array_two_reads",
   "ref_to_ref_in_array_write_through_call",
   "reference_alias_in_array",
   "reference_only_used_as_alias",
   "references",
   "regression_10452",
   "regression_10690",
   "regression_11134",
   "regression_11463",
   "regression_11540",
   "regression_12034",
   "regression_12467",
   "regression_12467_2",
   "regression_12473",
   "regression_12475",
   "regression_12494",
   "regression_12572",
   "regression_2660",
   "regression_3889",
   "regression_4088",
   "regression_4124",
   "regression_4202",
   "regression_7451",
   "regression_7836",
   "regression_7962",
   "regression_8210",
   "regression_8212",
   "regression_8305",
   "regression_8519",
   "regression_8726",
   "regression_8739",
   "regression_8761",
   "regression_8779",
   "regression_8890",
   "regression_8975",
   "regression_9102",
   "regression_9116",
   "regression_9206",
   "regression_9243",
   "regression_9329",
   "regression_9725_2",
   "regression_brillig_ref_deref_crash",
   "regression_foreign_proxy_generic",
   "regression_inner_if_else_collapse",
   "regression_loop_unroll_header_instructions",
   "regression_mem2reg_make_array_of_refs",
   "regression_noir_claude_1069",
   "regression_truncate_unchecked_sub",
   "regression_unused_nested_array_get",
   "return_twice",
   "shift_right_overflow",
   "shl_signed_regression_9661",
   "side_effects_constrain_array",
   "signed_arithmetic",
   "signed_bitshift",
   "signed_cmp",
   "signed_comparison",
   "signed_div",
   "signed_division",
   "signed_truncation",
   "simple_add_and_ret_arr",
   "simple_array_param",
   "simple_comparison",
   "simple_mut",
   "simple_not",
   "simple_program_addition",
   "simple_shift_left_right",
   "stored_unconstrained_fn_regression",
   "struct",
   "struct_array_inputs",
   "struct_assignment_with_shared_ref_to_field",
   "struct_fields_ordering",
   "struct_inputs",
   "trait_as_return_type",
   "trait_associated_constant",
   "trait_impl_base_type",
   "trait_sibling_bounds_associated_types",
   "traits_in_crates_1",
   "traits_in_crates_2",
   "tuple_inputs",
   "tuples",
   "type_aliases",
   "unary_operator_overloading",
   "unsafe_range_constraint",
   "unsigned_to_signed_cast",
   "vector_loop",
   "vector_pop_back_simplify",
   "vector_pop_temporary_alias",
   "wildcard_type",
   "witness_compression",
   "wrapping_operations",
   "zeroed_array_of_references"]

end AcirLean
