{
 "title": "Aztec Node",
 "description": "Stats from the Aztec Node",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Node status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(process_cpu_utilization)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory use",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_usage{system_memory_state=\"used\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current block height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aztec_archiver_block_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average block size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(aztec_archiver_block_size_sum[$__rate_interval]) / rate(aztec_archiver_block_size_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Average transaction size ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(aztec_mempool_tx_size_bytes_sum[$__rate_interval]) / rate(aztec_mempool_tx_size_bytes_count[$__rate_interval])",
     "legendFormat": "Tx size"
    }
   ]
  },
  {
   "title": "Transactions in mempool",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "aztec_mempool_tx_count", "legendFormat": "__auto" }
   ]
  }
 ]
}