{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": { "query": "label_values(exported_job)" } },
   { "name": "node", "label": "Node", "query": { "query": "label_values(exported_job)" } },
   { "name": "prover", "label": "Prover", "query": { "query": "label_values(exported_job)" } },
   {
    "name": "protocol_circuit",
    "label": "Protocol circuit",
    "query": {
     "query": "label_values(aztec_circuit_protocol_circuit_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization",
   "type": "stat",
   "description": "Percentage of total CPU bused",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(exported_job) (system_cpu_utilization{system_cpu_state=\"user\", exported_job=\"$node\"}) / count by(exported_job) (system_cpu_utilization{system_cpu_state=\"user\", exported_job=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "stat",
   "description": "Percentage of total system memory being used",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_utilization{exported_job=\"$node\", system_memory_state=\"used\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(system_network_io_total{exported_job=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{exported_job}} - {{network_io_direction}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(aztec_node_receive_tx_count{exported_job=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{aztec_ok}}"
    }
   ]
  },
  {
   "title": "Tx in mempool",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aztec_mempool_tx_count{exported_job=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx process time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(aztec_node_receive_tx_duration_milliseconds_sum{exported_job=\"$node\"}[$__rate_interval]) / on(aztec_ok) rate(aztec_node_receive_tx_duration_milliseconds_count{exported_job=\"$node\"}[$__rate_interval])",
     "legendFormat": "AVG"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aztec_node_receive_tx_duration_milliseconds_bucket{exported_job=\"$node\"}[$__rate_interval])))",
     "legendFormat": "95th Perc"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(aztec_node_receive_tx_duration_milliseconds_bucket{exported_job=\"$node\"}[$__rate_interval])))",
     "legendFormat": "50th Perc"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(aztec_node_receive_tx_duration_milliseconds_bucket{exported_job=\"$node\"}[$__rate_interval])))",
     "legendFormat": "MAX"
    }
   ]
  },
  { "title": "Sequencer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Blocks produced",
   "type": "stat",
   "description": "Total blocks produced and accepted by the rollup",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aztec_sequencer_block_build_ok_count{exported_job=\"$node\", aztec_ok=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block building duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aztec_sequencer_block_build_duration_milliseconds_bucket{exported_job=\"$node\"}[$__rate_interval])))",
     "legendFormat": "95th perc"
    }
   ]
  },
  {
   "title": "L1 transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(aztec_l1_publisher_tx_count{aztec_ok=\"true\"}[$__rate_interval])",
     "legendFormat": "L1 Tx \"{{aztec_l1_tx_type}}\""
    },
    {
     "expr": "sum(increase(aztec_l1_publisher_tx_count{aztec_ok=\"false\"}[$__rate_interval]))",
     "legendFormat": "Failed L1 txs"
    }
   ]
  },
  {
   "title": "Average gas cost gwei",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(aztec_l1_publisher_gas_price_gwei_sum[$__rate_interval]) / rate(aztec_l1_publisher_gas_price_gwei_count[$__rate_interval])",
     "legendFormat": "Avg gas price gwei"
    }
   ]
  },
  {
   "title": "Public function simuation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aztec_public_executor_simulation_duration_milliseconds_bucket{exported_job=\"$node\"}[$__rate_interval])))",
     "legendFormat": "95th Perc"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(aztec_public_executor_simulation_duration_milliseconds_bucket{exported_job=\"$node\"}[$__rate_interval])))",
     "legendFormat": "MAX"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(aztec_public_executor_simulation_duration_milliseconds_bucket{exported_job=\"$node\"}[$__rate_interval])))",
     "legendFormat": "50th Perc"
    },
    {
     "expr": "rate(aztec_public_executor_simulation_duration_milliseconds_sum{exported_job=\"$node\"}[$__rate_interval])/rate(aztec_public_executor_simulation_duration_milliseconds_count{exported_job=\"$node\"}[$__rate_interval])",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Public processor duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aztec_public_processor_tx_duration_milliseconds_bucket{exported_job=\"$node\"}[$__rate_interval])))",
     "legendFormat": "95th Perc"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(aztec_public_processor_tx_duration_milliseconds_bucket{exported_job=\"$node\"}[$__rate_interval])))",
     "legendFormat": "50th Perc"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aztec_public_processor_tx_duration_milliseconds_bucket{exported_job=\"$node\"}[$__rate_interval])))",
     "legendFormat": "MAX"
    },
    {
     "expr": "rate(aztec_public_processor_tx_duration_milliseconds_sum{exported_job=\"$node\"}[$__rate_interval]) / rate(aztec_public_processor_tx_duration_milliseconds_count{exported_job=\"$node\"}[$__rate_interval])",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Tx phase duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(aztec_public_processor_phase_duration_milliseconds_sum[$__rate_interval]) / rate(aztec_public_processor_phase_duration_milliseconds_count[$__rate_interval])",
     "legendFormat": "Avg {{aztec_tx_phase_name}}"
    }
   ]
  },
  {
   "title": "Deployed bytecode ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(aztec_public_executor_simulation_bytecode_size_bytes_sum[$__rate_interval]) / rate(aztec_public_executor_simulation_bytecode_size_bytes_count[$__rate_interval])",
     "legendFormat": "Avg bytes"
    }
   ]
  },
  {
   "title": "Merkle tree insertions before Base Rollup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(aztec_proving_orchestrator_base_rollup_inputs_duration_milliseconds_sum{exported_job=\"$node\"}[$__rate_interval]) / rate(aztec_proving_orchestrator_base_rollup_inputs_duration_milliseconds_count{exported_job=\"$node\"}[$__rate_interval])",
     "legendFormat": "AVG"
    }
   ]
  },
  { "title": "Prover Agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU utilization",
   "type": "stat",
   "description": "CPU usage as a percentage of all cores",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(exported_job) (system_cpu_utilization{system_cpu_state=\"user\", exported_job=\"$prover\"}) / count by(exported_job) (system_cpu_utilization{system_cpu_state=\"user\", exported_job=\"$prover\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "stat",
   "description": "Percentage of total system memory being used",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_utilization{exported_job=\"$prover\", system_memory_state=\"used\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(system_network_io_total{exported_job=\"$prover\"}[$__rate_interval])",
     "legendFormat": "{{exported_job}} - {{network_io_direction}}"
    }
   ]
  },
  { "title": "Witness generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Witness generation - $protocol_circuit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "repeat": "protocol_circuit",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(aztec_circuit_witness_generation_duration_milliseconds_sum{exported_job=\"$prover\", aztec_circuit_protocol_circuit_name=\"$protocol_circuit\"}[$__rate_interval]) / rate(aztec_circuit_witness_generation_duration_milliseconds_count{exported_job=\"$prover\"}[$__rate_interval])",
     "legendFormat": "Avg"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aztec_circuit_witness_generation_duration_milliseconds_bucket{exported_job=\"$prover\", aztec_circuit_protocol_circuit_name=\"$protocol_circuit\"}[$__rate_interval])))",
     "legendFormat": "95th Perc"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(aztec_circuit_witness_generation_duration_milliseconds_bucket{exported_job=\"$prover\", aztec_circuit_protocol_circuit_name=\"$protocol_circuit\"}[$__rate_interval])))",
     "legendFormat": "50th Perc"
    }
   ]
  },
  { "title": "Proving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Circuit proving - $protocol_circuit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "repeat": "protocol_circuit",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(aztec_circuit_proving_duration_milliseconds_sum{exported_job=\"$prover\", aztec_circuit_protocol_circuit_name=\"$protocol_circuit\"}[$__rate_interval]) / rate(aztec_circuit_proving_duration_milliseconds_count{exported_job=\"$prover\"}[$__rate_interval])",
     "legendFormat": "Avg"
    }
   ]
  }
 ]
}