VERSION 0.8

build:
    FROM ubuntu:focal

    # Install nginx
    COPY ./scripts/install_nginx.sh ./scripts/install_nginx.sh
    RUN ./scripts/install_nginx.sh

    # Install foundry
    COPY ./scripts/install_foundry.sh ./scripts/install_foundry.sh
    RUN ./scripts/install_foundry.sh
    ENV PATH="./foundry/bin:${PATH}"

    # Copy nginx config
    COPY ./scripts ./scripts
    COPY ./redeploy ./redeploy
    COPY ./nginx/ /etc/nginx/

    # Expose port 80
    EXPOSE 80

    # Set entrypoint.
    ENTRYPOINT ["sh", "-c", "./scripts/run_nginx_anvil.sh"]

export-local:
    FROM +build
    SAVE IMAGE aztecprotocol/mainnet-fork

export-mainnet-fork:
    FROM +build
    ARG DIST_TAG="devnet"
    ARG ARCH
    SAVE IMAGE --push aztecprotocol/mainnet-fork:${DIST_TAG}${ARCH:+-$ARCH}
