VERSION 0.8

build:
    FROM ubuntu:focal

    # Install nginx
    RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    RUN apt-get update && apt install -y git curl nginx

    # Copy nginx config
    COPY . .
    COPY nginx/gateway.conf /etc/nginx/gateway.conf
    COPY nginx/nginx.conf /etc/nginx/nginx.conf

    # Install foundry
    RUN ./scripts/install_foundry.sh
    ENV PATH="./foundry/bin:${PATH}"

    # Expose port 80
    EXPOSE 80

    # Set entrypoint.
    ENTRYPOINT ["sh", "-c", "./scripts/run_nginx_anvil.sh"]

export-mainnet-fork:
    FROM +build
    ARG DIST_TAG="aztec-dev"
    ARG ARCH
    SAVE IMAGE --push aztecprotocol/mainnet-fork:${DIST_TAG}${ARCH:+-$ARCH}
