FROM alpine:3.13 AS builder
RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
        build-base \
        cmake \
        git \
        curl
WORKDIR /usr/src/barretenberg
COPY . .
RUN mkdir build && cd build && cmake -DTOOLCHAIN=x86_64-linux-gcc -DDISABLE_HEAVY_TESTS=ON .. && make -j$(nproc)

FROM alpine:3.13
RUN apk update && apk add libstdc++ libgomp
COPY --from=builder /usr/src/barretenberg/build/src/aztec/rollup/db_cli/db_cli /usr/src/barretenberg/build/src/aztec/rollup/db_cli/db_cli
COPY --from=builder /usr/src/barretenberg/build/src/aztec/rollup/rollup_cli/rollup_cli /usr/src/barretenberg/build/src/aztec/rollup/rollup_cli/rollup_cli