FROM aztecprotocol/clang:9.0.0
RUN curl https://wasmtime.dev/install.sh -sSf | bash
WORKDIR /usr/src/barretenberg/src
RUN curl -s -L https://github.com/CraneStation/wasi-sdk/releases/download/wasi-sdk-8/wasi-sdk-8.0-linux.tar.gz | tar zxfv -
RUN sed -e '213i#include "../../../../wasi/stdlib-hook.h"' -i ./wasi-sdk-8.0/share/wasi-sysroot/include/stdlib.h
WORKDIR /usr/src/barretenberg
COPY . .
RUN mkdir build && cd build && cmake -DWASM=ON .. && make -j$(nproc) barretenberg.wasm
CMD cd build && make -j16 noir_tests && ~/.wasmtime/bin/wasmtime --dir=.. ./src/aztec/noir/compiler/noir_tests -- --gtest_filter=noir.sha256_NIST_one