FROM aztecprotocol/clang:9.0.0
WORKDIR /usr/src/barretenberg
COPY . .
RUN cd srs_db && ./download_ignition.sh 0
RUN mkdir build && cd build && cmake -DLINUX_CLANG=ON -DDISABLE_HEAVY_TESTS=ON .. && make -j$(nproc)
CMD cd build && make test