/-
Not trusted. Writes `AcirLean/Proofs/TestProgramCerts.lean`: for each test
program and each instruction of its body, the positions of a small set of
circuit constraints over which the checker's step gives the same result as
over the whole circuit. The kernel runs every step on the constraints listed
(`stepsWith`), so a wrong or stale certificate can only make a program fail to
prove. Run by `scripts/regen_programs.sh`; `scripts/check.sh` fails if the file
is out of date.
-/

import AcirLean.Proofs.Checker2
import AcirLean.Templates.TestPrograms

open AcirLean

/-- Positions in `keep` whose removal leaves `stepP`'s result unchanged are
dropped, in shrinking blocks. -/
partial def shrink (cc : List Opcode) (reps : Reps × Flag) (i : Instruction)
    (want : Option (Reps × Flag))
    (keep : Array ℕ) (block : ℕ) (at_ : ℕ) : Array ℕ :=
  if block == 0 then keep
  else if at_ ≥ keep.size then shrink cc reps i want keep (block / 2) 0
  else
    let trial := keep.extract 0 at_ ++ keep.extract (at_ + block) keep.size
    if stepP (pick cc trial.toList) reps i == want then shrink cc reps i want trial block at_
    else shrink cc reps i want keep block (at_ + block)

/-- One entry per instruction, as far as the checker gets. -/
def cert (e : TestProgram) : List (List ℕ) := Id.run do
  let cc := e.fn.opcodes
  let all := (List.range cc.length).toArray
  let some reps0 := initReps cc e.prog.params e.fn.parameters | return []
  let mut reps : Reps × Flag := (reps0, none)
  let mut out := #[]
  for i in e.prog.body do
    let want := stepP cc reps i
    match want with
    | none => return out.toList
    | some r =>
      out := out.push (shrink cc reps i want all (max 1 (all.size / 2)) 0).toList
      reps := r
  return out.toList

def main (args : List String) : IO Unit := do
  let mut s := "/-\nMACHINE-CHECKED: no review needed. Generated by `scripts/emit_certs.lean`;\n" ++
    "the kernel runs each step over the constraints listed (`stepsWith`).\n-/\n\n" ++
    "import AcirLean.Proofs.Checker2\n\nnamespace AcirLean\n\n" ++
    "def testProgramCerts : List (List (List ℕ)) := [\n"
  let certs := testPrograms.map cert
  s := s ++ ",\n".intercalate (certs.map fun c => s!"  {c}") ++ "]\n\nend AcirLean\n"
  match args with
  | [path] => IO.FS.writeFile path s
  | _ => IO.print s
