#!/usr/bin/env python3
"""Turn the `# corpus <i>` sections of the Rust pin output into Lean data.

Usage: gen_corpus.py <emitted.txt> > AcirLean/Templates/Corpus.lean

The output is not trusted: `check.sh` requires `templates.golden`, which Lean
prints from this data, to equal what `fv_templates.rs` emits.
"""
import re
import sys

HEADER = """/-
PINNED: no review needed. Generated by `scripts/gen_corpus.py` from the output
of `fv_templates.rs`; `templates.golden` (printed from this data by
`Spec/Pin.lean`) must equal that output, so the data cannot drift from what
`nargo compile` ships. `scripts/check.sh` allows only plain definitions here.
-/

import AcirLean.Spec.Programs

namespace AcirLean
"""


def parse_sections(text):
    sections, cur, name = [], [], None
    for line in text.splitlines():
        if line.startswith("# "):
            if name is not None:
                sections.append((name, cur))
            name, cur = line[2:], []
        else:
            cur.append(line)
    if name is not None:
        sections.append((name, cur))
    return [(n, body) for n, body in sections if n.startswith("corpus ")]


def lean_entry(idx, lines):
    width = int(re.search(r"v0: u(\d+)", lines[1]).group(1))
    nparams = lines[1].count(": u")
    body, i = [], 2
    while lines[i].startswith("    v") and "=" in lines[i]:
        m = re.match(r"    v\d+ = (div|lt) v(\d+), v(\d+)", lines[i])
        body.append(f"⟨.{m.group(1)}, {m.group(2)}, {m.group(3)}⟩")
        i += 1
    ret = int(re.match(r"    return v(\d+)", lines[i]).group(1))
    i += 2
    cs, witness = [], []
    for line in lines[i:]:
        if line.startswith("range "):
            _, w, k = line.split()
            cs.append(f".range {w} {k}")
        elif line.startswith("zero "):
            terms = []
            for t in line[5:].split(" + "):
                c, ws = t.split("*")
                terms.append(f"⟨{c}, {ws}⟩")
            cs.append(".zero [" + ", ".join(terms) + "]")
        elif line.startswith("inputs "):
            inputs = line[len("inputs "):]
        elif line.startswith("returns "):
            returns = line[len("returns "):]
        elif line.startswith("witness "):
            _, w, v = line.split()
            witness.append(f"({w}, {v})")
    return (
        f"def corpus{idx} : CorpusEntry where\n"
        f"  prog := {{ width := {width}, nparams := {nparams}, body := [{', '.join(body)}], ret := {ret} }}\n"
        f"  fn := {{ cs := [{', '.join(cs)}], inputs := {inputs}, returns := {returns} }}\n"
        f"  witness := [{', '.join(witness)}]\n"
    )


def main():
    sections = parse_sections(open(sys.argv[1]).read())
    out = [HEADER]
    for name, body in sections:
        out.append(lean_entry(int(name.split()[1]), body))
    names = ", ".join(f"corpus{int(n.split()[1])}" for n, _ in sections)
    out.append(f"def corpus : List CorpusEntry := [{names}]\n\nend AcirLean\n")
    print("\n".join(out))


main()
