FROM ubuntu:lunar
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y \
  build-essential \
  curl \
  git \
  cmake \
  lsb-release \
  wget \
  software-properties-common \
  gnupg \
  ninja-build \
  npm \
  pkg-config \
  libssl-dev \
  jq
RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 16
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN npm install -g yarn
WORKDIR /usr/src
COPY . .
RUN ./bootstrap.sh