#!/usr/bin/env bash

echo ✨ System Info  
sw_vers
echo ✨ System Details
uname -a
echo ✨ LLVM Version
llvm-config --version

echo ✨ CMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER
echo ✨ CMAKE_C_COMPILER=$CMAKE_C_COMPILER

# llvm@11 paths
export CC=/usr/local/opt/llvm@11/bin/clang
export CXX=/usr/local/opt/llvm@11/bin/clang++

export PATH="/usr/local/opt/llvm@11/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/llvm@11/lib"
export CPPFLAGS="-I/usr/local/opt/llvm@11/include"

echo ✨ clang -v
clang -v
echo ✨ clang++ -v
clang++ -v

echo ✨ LD_LIBRARY_PATH=$LD_LIBRARY_PATH

echo ✨ CC=$CC
echo ✨ CXX=$CXX
echo ✨ LIBS=$LIBS

# fix clang path's to bb expectations
sudo mkdir -p /usr/local/opt/llvm/bin/
sudo ln -s $(which $CC) /usr/local/opt/llvm/bin/clang
sudo ln -s $(which $CXX) /usr/local/opt/llvm/bin/clang++

#fix libomp path
sudo mkdir -p /usr/local/lib/
sudo ln -s /usr/local/Cellar/libomp/15.0.3/lib/libomp.a /usr/local/lib/libomp.a
ls /usr/local/Cellar/libomp/15.0.3/lib

echo ✨ /usr/local/opt/llvm/bin/clang --version
/usr/local/opt/llvm/bin/clang --version 
echo ✨ /usr/local/opt/llvm/bin/clang++ --version 
/usr/local/opt/llvm/bin/clang++ --version 

echo ✨ rustup target add x86_64-apple-darwin
rustup target add x86_64-apple-darwin

echo 👷 Cargo Build
cargo build --release --locked --target x86_64-apple-darwin