compressionLevel: mixed

enableGlobalCache: false

# Disable postinstall scripts to prevent potential security issues with untrusted packages.
# Packages that require postinstall scripts should be reviewed and added to the allowlist if necessary:
# https://yarnpkg.com/configuration/manifest#dependenciesMeta.built
enableScripts: false
npmMinimalAgeGate: 10080 # 1 week

logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.13.0.cjs
