FROM ubuntu:20.04
SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        build-essential \
        cmake \
        git \
        curl \
        clang \
        clang-format \
        pkg-config \
        libssl-dev \
        libomp-dev

WORKDIR /tmp

RUN curl https://sh.rustup.rs -sSf > rustup.sh
RUN chmod 755 rustup.sh
RUN ./rustup.sh -y
RUN rm /tmp/rustup.sh

ENV PATH "/root/.cargo/bin:$PATH"
RUN rustup --version; cargo --version; rustc --version;