FROM node:alpine3.17 as test
RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
        build-base \
        bash \
        git \
        jq \
        cargo
WORKDIR /usr/src/noir
COPY . .
RUN yarn install --frozen-lockfile
RUN yarn run build:noir_js