VERSION 0.8
# Produces a container that can be run to test a specific box. See docker-compose.yml.

build:
    # We need yarn. Start fresh container.
    FROM node:18.19.0
    RUN apt update && apt install netcat-openbsd
    COPY ../yarn-project+build/build /usr/src
    COPY ../noir/+nargo/nargo /usr/src/noir/noir-repo/target/release/nargo
    COPY ../noir-projects/+build/aztec-nr /usr/src/noir-projects/aztec-nr
    COPY ../noir-projects/+build/noir-protocol-circuits/crates/types /usr/src/noir-projects/noir-protocol-circuits/crates/types
    WORKDIR /usr/src/boxes
    COPY . .
    ENV AZTEC_NARGO=/usr/src/noir/noir-repo/target/release/nargo
    ENV AZTEC_CLI=/usr/src/yarn-project/cli/aztec-cli-dest
    RUN yarn && yarn build
    RUN npx -y playwright@1.42 install --with-deps
    ENTRYPOINT ["/bin/sh", "-c"]