mod append_only_tree_snapshot;

mod function_selector;
mod function_data;
mod function_leaf_preimage;

mod global_variables;

mod membership_witness;

mod new_contract_data;
mod nullifier_leaf_preimage;
mod contract_leaf_preimage;

mod block_header;
mod combined_constant_data;
mod nullifier_key_validation_request;
mod public_data_read;
mod public_data_update_request;
mod optionally_revealed_data;

mod combined_accumulated_data;

mod complete_address;

mod private_kernel;
mod kernel_circuit_public_inputs;
mod previous_kernel_data;

mod call_request;
mod call_stack_item;
mod call_context;

mod public_call_data;

mod public_circuit_public_inputs;
mod private_circuit_public_inputs;
mod side_effect;
