export class Bytes extends Buffer {}
export class Bytes1 extends Buffer {}
export class Bytes2 extends Buffer {}
export class Bytes3 extends Buffer {}
export class Bytes4 extends Buffer {}
export class Bytes5 extends Buffer {}
export class Bytes6 extends Buffer {}
export class Bytes7 extends Buffer {}
export class Bytes8 extends Buffer {}
export class Bytes9 extends Buffer {}
export class Bytes10 extends Buffer {}
export class Bytes11 extends Buffer {}
export class Bytes12 extends Buffer {}
export class Bytes13 extends Buffer {}
export class Bytes14 extends Buffer {}
export class Bytes15 extends Buffer {}
export class Bytes16 extends Buffer {}
export class Bytes17 extends Buffer {}
export class Bytes18 extends Buffer {}
export class Bytes19 extends Buffer {}
export class Bytes20 extends Buffer {}
export class Bytes21 extends Buffer {}
export class Bytes22 extends Buffer {}
export class Bytes23 extends Buffer {}
export class Bytes24 extends Buffer {}
export class Bytes25 extends Buffer {}
export class Bytes26 extends Buffer {}
export class Bytes27 extends Buffer {}
export class Bytes28 extends Buffer {}
export class Bytes29 extends Buffer {}
export class Bytes30 extends Buffer {}
export class Bytes31 extends Buffer {}
export class Bytes32 extends Buffer {}
