//! Struct definition collection and field resolution.

use std::collections::{BTreeMap, HashSet};

use iter_extended::vecmap;

use crate::{
    StructField,
    ast::NoirStruct,
    elaborator::{WildcardDisallowedContext, types::WildcardAllowed},
    hir::{
        def_collector::dc_crate::UnresolvedStruct, def_map::LocalModuleId,
        resolution::errors::ResolverError,
    },
    node_interner::{DependencyId, ReferenceId, TypeId},
};

use super::Elaborator;

/// Everything needed to resolve a struct's fields later, captured at
/// registration time. Mirrors [`super::function::UnresolvedFunctionMeta`] for
/// function metas. The actual `DataType` already lives in the interner; this
/// just holds the syntactic struct definition plus the module context.
pub(super) struct UnresolvedStructFields {
    pub(super) struct_def: NoirStruct,
    pub(super) module_id: LocalModuleId,
}

impl Elaborator<'_> {
    /// Collects all struct definitions and either resolves their fields eagerly
    /// (in the stdlib) or registers them for lazy resolution (in user crates,
    /// so that struct fields can reference types generated by comptime attribute expansion).
    ///
    /// The per-struct checks that need resolved fields
    /// (visibility, LSP definition-location registration, ABI mark-as-used,
    /// `must_use` propagation) run inside [`Self::resolve_one_struct_fields`]
    /// in both paths, so they fire as soon as fields are available. The
    /// whole-program `check_for_nested_vectors` runs separately in
    /// [`Self::check_for_nested_vectors_in`] from `elaborate_items`, after
    /// the post-attribute drain has filled in every field.
    #[tracing::instrument(level = "trace", skip_all)]
    pub(super) fn collect_struct_definitions(
        &mut self,
        structs: &BTreeMap<TypeId, UnresolvedStruct>,
    ) {
        if self.crate_id.is_stdlib() {
            // Stdlib does not generate types via comptime attributes, so deferral isn't needed here.
            for (type_id, typ) in structs {
                self.resolve_one_struct_fields(*type_id, typ.module_id, &typ.struct_def);
            }
        } else {
            // Deferred flow: register only. The field types will be resolved
            // lazily on first read (via [Self::define_struct_fields_if_undefined])
            // or in the post-attribute drain.
            for (type_id, typ) in structs {
                self.unresolved_struct_fields.insert(
                    *type_id,
                    UnresolvedStructFields {
                        struct_def: typ.struct_def.clone(),
                        module_id: typ.module_id,
                    },
                );
            }
        }
    }

    /// If `type_id` was registered for deferred field resolution, resolve it
    /// now. No-op for structs whose fields have already been resolved (either
    /// eagerly in the stdlib path or by a previous lazy resolve).
    pub(crate) fn define_struct_fields_if_undefined(&mut self, type_id: TypeId) {
        let Some(info) = self.unresolved_struct_fields.remove(&type_id) else {
            return;
        };
        self.resolve_one_struct_fields(type_id, info.module_id, &info.struct_def);
    }

    /// Drains every remaining unresolved struct's fields, except those listed
    /// in `skip`.
    #[tracing::instrument(level = "trace", skip_all)]
    pub(super) fn resolve_unresolved_struct_fields_skipping(&mut self, skip: &HashSet<TypeId>) {
        let to_resolve: Vec<TypeId> =
            self.unresolved_struct_fields.keys().copied().filter(|id| !skip.contains(id)).collect();
        for type_id in to_resolve {
            self.define_struct_fields_if_undefined(type_id);
        }
    }

    /// Resolves a single struct's fields and runs the per-struct checks that
    /// require the resolved field list (visibility, LSP, ABI mark-as-used,
    /// `must_use`). Used by both the eager stdlib path and the lazy/deferred
    /// path for non-stdlib crates.
    fn resolve_one_struct_fields(
        &mut self,
        type_id: TypeId,
        module_id: LocalModuleId,
        struct_def: &NoirStruct,
    ) {
        let previous_local_module = self.replace_local_module(module_id);
        let previous_current_item = self.current_item.take();
        self.current_item = Some(DependencyId::DataType(type_id));

        let previous_in_comptime_context =
            std::mem::replace(&mut self.in_comptime_context, struct_def.comptime);

        // Struct fields are resolved at the module level: clear any generics
        // that an outer caller may have in scope (e.g. when lazy resolution
        // is triggered from inside an impl method, the impl's generics would
        // otherwise collide with the struct's via `add_existing_generics`).
        let previous_generics = std::mem::take(&mut self.generics);

        let fields = self.resolve_struct_fields(struct_def, type_id);

        if struct_def.is_abi() {
            for field in &fields {
                self.mark_type_as_used(&field.typ);
            }
        }

        self.check_struct_field_type_visibility(struct_def, &fields);

        if self.interner.is_in_lsp_mode() {
            for (field_index, field) in fields.iter().enumerate() {
                let location = field.name.location();
                let reference_id = ReferenceId::StructMember(type_id, field_index);
                self.interner.add_definition_location(reference_id, location);
            }
        }

        self.interner.update_type(type_id, |struct_def_in_interner| {
            let mut attributes = struct_def.attributes.iter();
            if let Some(message) = attributes.find_map(|attr| attr.kind.must_use_message()) {
                struct_def_in_interner.must_use = crate::MustUse::MustUse(message);
            }
            struct_def_in_interner.set_fields(fields);
        });

        self.generics = previous_generics;
        self.in_comptime_context = previous_in_comptime_context;
        self.current_item = previous_current_item;
        self.local_module = previous_local_module;
    }

    /// Resolves the field types for a single struct definition.
    ///
    /// This method:
    /// - Sets up the generic context from the struct's generic parameters
    /// - Resolves each field's type in the context of the struct's generics
    /// - Tracks the struct id to detect circular dependencies
    ///
    /// The generic scope is automatically recovered after resolution completes.
    #[tracing::instrument(level = "trace", skip_all)]
    fn resolve_struct_fields(
        &mut self,
        unresolved: &NoirStruct,
        struct_id: TypeId,
    ) -> Vec<StructField> {
        self.recover_generics(|this| {
            let previous_item = this.current_item.replace(DependencyId::DataType(struct_id));

            this.resolving_ids.insert(struct_id);

            let struct_def = this.interner.get_type(struct_id);
            this.add_existing_generics(&unresolved.generics, &struct_def.borrow().generics);

            let wildcard_allowed = WildcardAllowed::No(WildcardDisallowedContext::StructField);
            let previous_impl_trait_context = this
                .impl_trait_is_disallowed
                .replace(super::types::ImplTraitDisallowedContext::StructField);
            let fields = vecmap(&unresolved.fields, |field| {
                let visibility = field.item.visibility;
                let name = field.item.name.clone();
                let typ = this.resolve_type(field.item.typ.clone(), wildcard_allowed);
                StructField { visibility, name, typ }
            });
            this.impl_trait_is_disallowed = previous_impl_trait_context;

            this.resolving_ids.remove(&struct_id);

            this.current_item = previous_item;

            fields
        })
    }

    /// Checks all resolved structs for nested vector types, which are not allowed.
    ///
    /// This check must happen after all struct fields are resolved to ensure we have
    /// complete type information. We only check structs without generics here, as
    /// generic structs are validated during monomorphization and after monomorphization
    /// during SSA codegen.
    #[tracing::instrument(level = "trace", skip_all)]
    pub(super) fn check_for_nested_vectors_in(
        &mut self,
        structs: &BTreeMap<TypeId, UnresolvedStruct>,
    ) {
        for id in structs.keys() {
            let struct_type = self.interner.get_type(*id);

            // Only handle structs without generics as any generics args will be checked
            // after monomorphization when performing SSA codegen
            if struct_type.borrow().generics.is_empty() {
                // Every struct in `structs` belongs to this `elaborate_items`
                // call, and the post-attribute struct-field drain runs before
                // `check_for_nested_vectors_in`, so their fields must be
                // resolved by now (outer-pending structs are in the outer
                // call's `items.structs`, not ours).
                let fields = struct_type
                    .borrow()
                    .get_fields(&[])
                    .expect("struct fields should be resolved before nested-vector check");
                for (_, field_type, _) in &fields {
                    if field_type.is_nested_vector() {
                        let location = struct_type.borrow().location;
                        self.push_err(ResolverError::NestedVectors { location });
                    }
                }
            }
        }
    }
}
