#[allow(unused_imports)]
#[cfg(test)]
mod tests {
    // Some of these imports are consumed by the injected tests
    use assert_cmd::prelude::*;
    use tempdir::TempDir;

    use std::collections::BTreeMap;
    use std::fs;
    use std::path::PathBuf;
    use std::process::Command;

    use super::*;

    // include tests generated by `build.rs`
    include!(concat!(env!("OUT_DIR"), "/prove_and_verify.rs"));
}
