/-
MACHINE-CHECKED: no review needed. Generated by `scripts/emit_hint_certs.lean`.
-/

import AcirLean.Proofs.HintChecker
import AcirLean.Templates.TestPrograms

namespace AcirLean

set_option linter.all false
set_option maxRecDepth 100000
set_option maxHeartbeats 0

-- brillig_mutable_reference_lsf_bug
def circ21 : Circ := ⟨[], (.node .leaf (.assertZero [⟨1, []⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [0]⟩]) .leaf), 1⟩

theorem p21_link :
    checkProgSteps prog21.prog prog21.fn circ21
      []
      [] = true := by
  decide +kernel

-- field_attribute
def circ53 : Circ := ⟨[], (.node (.node (.node .leaf (.range 0 32) .leaf) (.range 2 32) .leaf) (.assertZero [⟨4294967297, []⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [0]⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186571513528321, [1]⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [2]⟩]) (.node .leaf (.assertZero [⟨1, [1]⟩]) .leaf)), 4⟩

def rv53_0 : RVal := (.scalar ⟨[[⟨1, [0]⟩]], (.uint 32), 0, 4294967295⟩)
def rv53_1 : RVal := (.scalar ⟨[[⟨1, []⟩, ⟨(-1), [1]⟩], [⟨1, []⟩]], (.uint 1), 0, 1⟩)
def sc53_0 : StepCert :=
  ⟨(.bin 2 .lt false (.const 1 (.uint 32)) (.var 0)), ⟨[1, 2, 3], none, some ([⟨1, []⟩], 0, [⟨(.con 3), [], 1⟩]), none⟩, [(0, rv53_0)], none, none, [(2, rv53_1)]⟩
theorem p53_step0 : (sc53_0).ok circ53 = true := by decide +kernel

def sc53_1 : StepCert :=
  ⟨(.constrain (.var 2) (.const 1 (.uint 1)) none), ⟨[], none, none, none⟩, [(2, rv53_1)], none, none, []⟩
theorem p53_step1 : (sc53_1).ok circ53 = true := by decide +kernel

theorem p53_link :
    checkProgSteps prog53.prog prog53.fn circ53
      [sc53_0, sc53_1]
      [] = true := by
  decide +kernel

-- nested_array_with_refs
def circ85 : Circ := ⟨[], (.node .leaf (.assertZero [⟨1, [0]⟩]) .leaf), 1⟩

theorem p85_link :
    checkProgSteps prog85.prog prog85.fn circ85
      []
      [] = true := by
  decide +kernel

-- regression_12572
def circ117 : Circ := ⟨[], (.node .leaf (.assertZero [⟨1, [0]⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [1]⟩]) .leaf), 1⟩

theorem p117_link :
    checkProgSteps prog117.prog prog117.fn circ117
      []
      [] = true := by
  decide +kernel

-- regression_9243
def circ149 : Circ := ⟨[], .leaf, 0⟩

theorem p149_link :
    checkProgSteps prog149.prog prog149.fn circ149
      []
      [] = true := by
  decide +kernel

-- simple_array_param
def circ181 : Circ := ⟨[], (.node .leaf (.assertZero [⟨1, [1]⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [2]⟩]) .leaf), 1⟩

def rv181_0 : RVal := (.array [⟨[[⟨1, [0]⟩]], .field, 0, 21888242871839275222246405745257275088548364400416034343698204186575808495616⟩, ⟨[[⟨1, [1]⟩]], .field, 0, 21888242871839275222246405745257275088548364400416034343698204186575808495616⟩])
def rv181_1 : RVal := (.scalar ⟨[[⟨1, [1]⟩]], .field, 0, 21888242871839275222246405745257275088548364400416034343698204186575808495616⟩)
def sc181_0 : StepCert :=
  ⟨(.arrayGet 2 (.var 0) (.const 1 (.uint 32)) .field), ⟨[], none, none, none⟩, [(0, rv181_0)], none, none, [(2, rv181_1)]⟩
theorem p181_step0 : (sc181_0).ok circ181 = true := by decide +kernel

theorem p181_link :
    checkProgSteps prog181.prog prog181.fn circ181
      [sc181_0]
      [] = true := by
  decide +kernel

end AcirLean
