/-
MACHINE-CHECKED: no review needed. Generated by `scripts/emit_hint_certs.lean`.
-/

import AcirLean.Proofs.HintChecker
import AcirLean.Templates.TestPrograms

namespace AcirLean

set_option linter.all false
set_option maxRecDepth 100000
set_option maxHeartbeats 0

-- closures_mut_ref
def circ27 : Circ := ⟨[], (.node .leaf (.assertZero [⟨1, [0]⟩]) .leaf), 1⟩

def rv27_0 : RVal := (.scalar ⟨[[⟨1, [0]⟩]], .field, 0, 21888242871839275222246405745257275088548364400416034343698204186575808495616⟩)
def rv27_1 : RVal := (.scalar ⟨[[⟨1, [0]⟩, ⟨1, []⟩], [⟨1, []⟩]], .field, 0, 21888242871839275222246405745257275088548364400416034343698204186575808495616⟩)
def sc27_0 : StepCert :=
  ⟨(.bin 2 .add false (.var 0) (.const 1 .field)), ⟨[], none, some ([⟨1, []⟩], 0, [⟨(.con 0), [], 21888242871839275222246405745257275088548364400416034343698204186575808495616⟩]), none⟩, [(0, rv27_0)], none, none, [(2, rv27_1)]⟩
theorem p27_step0 : (sc27_0).ok circ27 = true := by decide +kernel

def sc27_1 : StepCert :=
  ⟨(.constrain (.var 2) (.const 1 .field) none), ⟨[], none, none, none⟩, [(2, rv27_1)], none, none, []⟩
theorem p27_step1 : (sc27_1).ok circ27 = true := by decide +kernel

theorem p27_link :
    checkProgSteps prog27.prog prog27.fn circ27
      [sc27_0, sc27_1]
      [] = true := by
  decide +kernel

-- generics
def circ59 : Circ := ⟨[], (.node .leaf (.assertZero [⟨1, [0]⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [1]⟩]) .leaf), 1⟩

def rv59_0 : RVal := (.scalar ⟨[[⟨1, [0]⟩]], .field, 0, 21888242871839275222246405745257275088548364400416034343698204186575808495616⟩)
def rv59_1 : RVal := (.scalar ⟨[[⟨1, [1]⟩]], .field, 0, 21888242871839275222246405745257275088548364400416034343698204186575808495616⟩)
def sc59_0 : StepCert :=
  ⟨(.constrain (.var 0) (.var 1) none), ⟨[0], none, none, none⟩, [(0, rv59_0), (1, rv59_1)], none, none, []⟩
theorem p59_step0 : (sc59_0).ok circ59 = true := by decide +kernel

theorem p59_link :
    checkProgSteps prog59.prog prog59.fn circ59
      [sc59_0]
      [] = true := by
  decide +kernel

-- operator_overload_in_global
def circ91 : Circ := ⟨[], (.node .leaf (.assertZero [⟨1, []⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [0]⟩]) .leaf), 1⟩

def rv91_0 : RVal := (.scalar ⟨[[⟨1, [0]⟩]], .field, 0, 21888242871839275222246405745257275088548364400416034343698204186575808495616⟩)
def sc91_0 : StepCert :=
  ⟨(.constrain (.var 3) (.const 1 .field) none), ⟨[0], none, none, none⟩, [(3, rv91_0)], none, none, []⟩
theorem p91_step0 : (sc91_0).ok circ91 = true := by decide +kernel

theorem p91_link :
    checkProgSteps prog91.prog prog91.fn circ91
      [sc91_0]
      [] = true := by
  decide +kernel

-- regression_4202
def circ123 : Circ := ⟨[], (.node (.node (.node .leaf (.assertZero [⟨1, []⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [0]⟩]) .leaf) (.assertZero [⟨2, []⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [1]⟩]) .leaf) (.assertZero [⟨3, []⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [2]⟩]) (.node .leaf (.assertZero [⟨4, []⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [3]⟩]) .leaf)), 4⟩

def rv123_0 : RVal := (.array [⟨[[⟨1, [0]⟩]], (.uint 32), 1, 1⟩, ⟨[[⟨1, [1]⟩]], (.uint 32), 2, 2⟩, ⟨[[⟨1, [2]⟩]], (.uint 32), 3, 3⟩, ⟨[[⟨1, [3]⟩]], (.uint 32), 4, 4⟩])
def rv123_1 : RVal := (.scalar ⟨[[⟨1, [0]⟩], [⟨1, []⟩]], (.uint 32), 1, 1⟩)
def sc123_0 : StepCert :=
  ⟨(.arrayGet 2 (.var 0) (.const 0 (.uint 32)) (.uint 32)), ⟨[], none, some ([⟨1, []⟩], 0, [⟨(.con 0), [], 1⟩]), none⟩, [(0, rv123_0)], none, none, [(2, rv123_1)]⟩
theorem p123_step0 : (sc123_0).ok circ123 = true := by decide +kernel

def sc123_1 : StepCert :=
  ⟨(.constrain (.const 1 (.uint 32)) (.var 2) none), ⟨[], none, none, none⟩, [(2, rv123_1)], none, none, []⟩
theorem p123_step1 : (sc123_1).ok circ123 = true := by decide +kernel

def rv123_2 : RVal := (.scalar ⟨[[⟨1, [1]⟩], [⟨2, []⟩]], (.uint 32), 2, 2⟩)
def sc123_2 : StepCert :=
  ⟨(.arrayGet 4 (.var 0) (.const 1 (.uint 32)) (.uint 32)), ⟨[], none, some ([⟨2, []⟩], 0, [⟨(.con 1), [], 1⟩]), none⟩, [(0, rv123_0)], none, none, [(4, rv123_2)]⟩
theorem p123_step2 : (sc123_2).ok circ123 = true := by decide +kernel

def sc123_3 : StepCert :=
  ⟨(.constrain (.const 2 (.uint 32)) (.var 4) none), ⟨[], none, none, none⟩, [(4, rv123_2)], none, none, []⟩
theorem p123_step3 : (sc123_3).ok circ123 = true := by decide +kernel

def rv123_3 : RVal := (.scalar ⟨[[⟨1, [2]⟩], [⟨3, []⟩]], (.uint 32), 3, 3⟩)
def sc123_4 : StepCert :=
  ⟨(.arrayGet 6 (.var 0) (.const 2 (.uint 32)) (.uint 32)), ⟨[], none, some ([⟨3, []⟩], 0, [⟨(.con 2), [], 1⟩]), none⟩, [(0, rv123_0)], none, none, [(6, rv123_3)]⟩
theorem p123_step4 : (sc123_4).ok circ123 = true := by decide +kernel

def sc123_5 : StepCert :=
  ⟨(.constrain (.const 3 (.uint 32)) (.var 6) none), ⟨[], none, none, none⟩, [(6, rv123_3)], none, none, []⟩
theorem p123_step5 : (sc123_5).ok circ123 = true := by decide +kernel

def rv123_4 : RVal := (.scalar ⟨[[⟨1, [3]⟩], [⟨4, []⟩]], (.uint 32), 4, 4⟩)
def sc123_6 : StepCert :=
  ⟨(.arrayGet 8 (.var 0) (.const 3 (.uint 32)) (.uint 32)), ⟨[], none, some ([⟨4, []⟩], 0, [⟨(.con 3), [], 1⟩]), none⟩, [(0, rv123_0)], none, none, [(8, rv123_4)]⟩
theorem p123_step6 : (sc123_6).ok circ123 = true := by decide +kernel

def sc123_7 : StepCert :=
  ⟨(.constrain (.const 4 (.uint 32)) (.var 8) none), ⟨[], none, none, none⟩, [(8, rv123_4)], none, none, []⟩
theorem p123_step7 : (sc123_7).ok circ123 = true := by decide +kernel

theorem p123_link :
    checkProgSteps prog123.prog prog123.fn circ123
      [sc123_0, sc123_1, sc123_2, sc123_3, sc123_4, sc123_5, sc123_6, sc123_7]
      [] = true := by
  decide +kernel

-- regression_9764
def circ155 : Circ := ⟨[], (.node (.node (.node .leaf (.range 1 32) .leaf) (.assertZero [⟨1, []⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [0, 3]⟩, ⟨1, [3]⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [4]⟩]) .leaf) (.assertZero [⟨1, [0, 4]⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [4]⟩]) (.node (.node .leaf (.assertZero [⟨1, []⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [0]⟩]) .leaf) (.assertZero [⟨1, [0]⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [0, 4]⟩, ⟨21888242871839275222246405745257275088548364400416034343698204186575808495616, [2]⟩]) .leaf)), 5⟩

def rv155_0 : RVal := (.scalar ⟨[[⟨1, [0]⟩]], .field, 0, 21888242871839275222246405745257275088548364400416034343698204186575808495616⟩)
def rv155_1 : RVal := (.scalar ⟨[[⟨1, [0]⟩], [⟨1, [0]⟩], [⟨1, [4]⟩]], (.uint 1), 0, 1⟩)
def sc155_0 : StepCert :=
  ⟨(.bin 3 .eq false (.var 0) (.const 1 .field)), ⟨[1, 2, 3], none, none, none⟩, [(0, rv155_0)], none, none, [(3, rv155_1)]⟩
theorem p155_step0 : (sc155_0).ok circ155 = true := by decide +kernel

def rv155_2 : RVal := (.scalar ⟨[[⟨1, []⟩, ⟨(-1), [0]⟩], [⟨1, []⟩, ⟨(-1), [0]⟩], [⟨1, []⟩, ⟨(-1), [4]⟩]], (.uint 1), 0, 1⟩)
def sc155_1 : StepCert :=
  ⟨(.not 4 (.var 3)), ⟨[], none, none, none⟩, [(3, rv155_1)], none, none, [(4, rv155_2)]⟩
theorem p155_step1 : (sc155_1).ok circ155 = true := by decide +kernel

def sc155_2 : StepCert :=
  ⟨(.enableSideEffects (.var 4)), ⟨[4], none, none, none⟩, [(4, rv155_2)], none, (some ([⟨1, []⟩, ⟨(-1), [0]⟩], [(0, 0), (4, 0), (2, 0)])), []⟩
theorem p155_step2 : (sc155_2).ok circ155 = true := by decide +kernel

def sc155_3 : StepCert :=
  ⟨(.constrain (.var 0) (.const 1 .field) (some "Index out of bounds")), ⟨[3], none, none, none⟩, [(0, rv155_0)], (some ([⟨1, []⟩, ⟨(-1), [0]⟩], [(0, 0), (4, 0), (2, 0)])), (some ([⟨1, []⟩, ⟨(-1), [0]⟩], [(0, 0), (4, 0), (2, 0)])), []⟩
theorem p155_step3 : (sc155_3).ok circ155 = true := by decide +kernel

def sc155_4 : StepCert :=
  ⟨(.enableSideEffects (.const 1 (.uint 1))), ⟨[], none, none, none⟩, [], (some ([⟨1, []⟩, ⟨(-1), [0]⟩], [(0, 0), (4, 0), (2, 0)])), none, []⟩
theorem p155_step4 : (sc155_4).ok circ155 = true := by decide +kernel

def rv155_3 : RVal := (.scalar ⟨[[⟨1, []⟩, ⟨(-1), [0]⟩], [⟨1, []⟩, ⟨(-1), [0]⟩], [⟨1, []⟩, ⟨(-1), [4]⟩]], .field, 0, 1⟩)
def sc155_5 : StepCert :=
  ⟨(.cast 6 (.var 4) .field), ⟨[], none, none, none⟩, [(4, rv155_2)], none, none, [(6, rv155_3)]⟩
theorem p155_step5 : (sc155_5).ok circ155 = true := by decide +kernel

def rv155_4 : RVal := (.scalar ⟨[[⟨1, [0]⟩, ⟨(-1), [0, 0]⟩], [⟨1, [0]⟩, ⟨(-1), [4, 0]⟩]], .field, 0, 21888242871839275222246405745257275088548364400416034343698204186575808495616⟩)
def sc155_6 : StepCert :=
  ⟨(.bin 7 .mul false (.var 6) (.var 0)), ⟨[], none, none, none⟩, [(6, rv155_3), (0, rv155_0)], none, none, [(7, rv155_4)]⟩
theorem p155_step6 : (sc155_6).ok circ155 = true := by decide +kernel

theorem p155_link :
    checkProgSteps prog155.prog prog155.fn circ155
      [sc155_0, sc155_1, sc155_2, sc155_3, sc155_4, sc155_5, sc155_6]
      [] = true := by
  decide +kernel

-- stored_unconstrained_fn_regression
def circ187 : Circ := ⟨[], .leaf, 0⟩

theorem p187_link :
    checkProgSteps prog187.prog prog187.fn circ187
      []
      [] = true := by
  decide +kernel

end AcirLean
