FROM 278380418400.dkr.ecr.eu-west-2.amazonaws.com/yarn-project-prod
WORKDIR /usr/src/yarn-project/aztec-faucet
ENTRYPOINT ["node", "--no-warnings", "/usr/src/yarn-project/aztec-faucet/dest/bin/index.js"]
EXPOSE 8080
