VERSION 0.8

deps:
    LOCALLY
    LET packages = $(git ls-files "**/package*.json" package*.json)
    LET tsconfigs = $(git ls-files "**/tsconfig*.json" tsconfig*.json)
    FROM ../build-images+build
    # copy bb-js and noir-packages
    COPY ../barretenberg/ts/+build/build /usr/src/barretenberg/ts
    COPY ../noir/+packages/packages /usr/src/noir/packages
    WORKDIR /usr/src/yarn-project
    COPY --dir .yarn .yarnrc.yml yarn.lock .
    FOR file IN $packages
        COPY $file $file
    END
    RUN yarn install --immutable
    FOR file IN $tsconfigs
        COPY $file $file
    END
    COPY scripts/update_package_jsons.mjs scripts/update_package_jsons.mjs
    RUN yarn prepare:check

    # We install a symlink to yarn-project's node_modules at a location that all portalled packages can find as they
    # walk up the tree as part of module resolution. The supposedly idiomatic way of supporting module resolution
    # correctly for portalled packages, is to use --preserve-symlinks when running node.
    # This does kind of work, but jest doesn't honor it correctly, so this seems like a neat workaround.
    # Also, --preserve-symlinks causes duplication of portalled instances such as bb.js, and breaks the singleton logic
    # by initialising the module more than once. So at present I don't see a viable alternative.
    RUN ln -s /usr/src/yarn-project/node_modules /usr/src/node_modules

build:
    # Prefetch targets to not wait for +deps.
    BUILD ../barretenberg/cpp/+preset-release
    BUILD ../noir/+nargo
    BUILD ../noir-projects/+build
    BUILD ../l1-contracts/+build
    FROM +deps

    COPY ../barretenberg/cpp/+preset-release/bin/bb /usr/src/barretenberg/cpp/build/bin/bb
    COPY ../noir/+nargo/acvm /usr/src/noir/noir-repo/target/release/acvm
    COPY --dir ../noir-projects/+build/. /usr/src/noir-projects
    COPY ../l1-contracts/+build/usr/src/l1-contracts /usr/src/l1-contracts

    WORKDIR /usr/src/yarn-project
    COPY . .
    ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    RUN ./bootstrap.sh full

build-dev:
    FROM +build
    SAVE ARTIFACT /usr/src /usr/src

aztec-prod:
    FROM +build
    RUN yarn workspaces focus @aztec/aztec --production && yarn cache clean
    # Remove a bunch of stuff that we don't need that takes up space.
    RUN rm -rf \
        ../noir-projects \
        ../l1-contracts \
        ../barretenberg/ts/src \
        ../barretenberg/ts/dest/node-cjs \
        ../barretenberg/ts/dest/browser \
        aztec.js/dest/main.js \
        end-to-end \
        **/src \
        **/artifacts
    SAVE ARTIFACT /usr/src /usr/src

aztec:
    FROM ubuntu:noble
    RUN apt update && apt install nodejs -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    COPY +aztec-prod/usr/src /usr/src
    LET port=8080
    ENV PORT=$port
    HEALTHCHECK --interval=10s --timeout=10s --retries=6 \
        CMD curl -fsSd '{\"jsonrpc\":\"2.0\",\"method\":\"pxe_getNodeInfo\",\"id\":1}' http://127.0.0.1:$port
    ENTRYPOINT ["node", "--no-warnings", "/usr/src/yarn-project/aztec/dest/bin/index.js"]
    EXPOSE $port

# We care about creating a slimmed down e2e image because we have to serialize it from earthly to docker for running.
end-to-end-prod:
    FROM +build
    RUN yarn workspaces focus @aztec/end-to-end --production && yarn cache clean
    # Remove a bunch of stuff that we don't need that takes up space.
    RUN rm -rf \
        ../noir-projects \
        ../l1-contracts \
        ../barretenberg/ts/src \
        ../barretenberg/ts/dest/node-cjs \
        ../barretenberg/ts/dest/browser \
        **/artifacts
    SAVE ARTIFACT /usr/src /usr/src

end-to-end:
    FROM ubuntu:noble
    RUN apt-get update && apt-get install -y wget gnupg \
        && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
        && echo "deb [arch=$(dpkg --print-architecture)] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
        && apt update && apt install nodejs jq google-chrome-stable netcat-openbsd -y \
        && rm -rf /var/lib/apt/lists/*
    ENV CHROME_BIN="/usr/bin/google-chrome-stable"
    ENV PATH=/opt/foundry/bin:$PATH
    COPY ../build-images+build/anvil /opt/foundry/bin/anvil
    COPY +end-to-end-prod/usr/src /usr/src
    WORKDIR /usr/src/yarn-project/end-to-end
    RUN ln -s /usr/src/yarn-project/.yarn/releases/yarn-3.6.3.cjs /usr/local/bin/yarn
    ENTRYPOINT ["yarn", "test"]

scripts-prod:
    FROM +build
    RUN yarn workspaces focus @aztec/scripts --production && yarn cache clean
    SAVE ARTIFACT /usr/src /usr/src

all:
    BUILD +aztec
    BUILD +end-to-end

export-aztec:
    ARG EARTHLY_GIT_HASH
    FROM +aztec
    SAVE IMAGE aztecprotocol/aztec:$EARTHLY_GIT_HASH

export-end-to-end:
    ARG EARTHLY_GIT_HASH
    FROM +end-to-end
    SAVE IMAGE aztecprotocol/end-to-end:$EARTHLY_GIT_HASH

format-check:
    FROM +build
    RUN yarn formatting

test:
    FROM +build
    RUN yarn test

run-e2e:
    ARG test
    FROM +end-to-end
    RUN DEBUG=aztec:* yarn test $test
