VERSION 0.8
FROM ubuntu:lunar
RUN apt update && apt install curl git jq bash nodejs npm python3.11-full python3-pip -y

# Use virtualenv, do not try to use pipx, it's not working.
RUN python3 -m venv /root/.venv
RUN /root/.venv/bin/pip3 install slither-analyzer==0.10.0 slitherin==0.5.0
RUN curl -L https://foundry.paradigm.xyz | bash

# Set env variables for foundry and venv
ENV PATH="${PATH}:/root/.foundry/bin:/root/.venv/bin"
RUN foundryup

# Install yarn and solhint.
RUN npm install --global yarn solhint

WORKDIR /usr/src
COPY --dir lib scripts src terraform test *.json *.toml *.sh .

build:
    RUN git init && git add . && yarn lint && yarn slither && yarn slither-has-diff
    RUN forge clean && forge fmt --check && forge build && forge test --no-match-contract UniswapPortalTest
    SAVE ARTIFACT out
