VERSION 0.8

build:
    FROM ../build-images+from-registry
    WORKDIR /usr/src/l1-contracts
    COPY --dir lib src terraform test *.json *.toml *.sh .
    #RUN git init && git add . && yarn lint && yarn slither && yarn slither-has-diff
    # "slither": "forge clean && forge build --build-info --skip '*/test/**' --force && slither . --checklist --ignore-compile --show-ignored-findings --config-file ./slither.config.json | tee slither_output.md",
    # "slither-has-diff": "./slither_has_diff.sh"
    RUN solhint --config ./.solhint.json --fix "src/**/*.sol"
    RUN forge clean && forge fmt --check
    RUN forge build
    SAVE ARTIFACT /usr/src/l1-contracts /usr/src/l1-contracts

test:
    FROM +build
    RUN forge test --no-match-contract UniswapPortalTest
