#!/bin/bash
set -exu

# To be called from CI for testing with docker and AWS.
# Can't be called locally unless AWS credentials are set up.
#
# Call from config.yml
# Example:
#   command: cond_spot_run_tests circuits-wasm-linux-clang-assert 1 wasm scripts/a3-tests -*.skip*:*.circuit*


###############################################################################
# ARGS
###############################################################################
NUM_TRANSCRIPTS=$1 # integer (MANDATORY)
ARCH=$2 # x86_64 or wasm (MUST BE LOWERCASE) (MANDATORY) used in `run_tests_local`
# TESTS=$3 (MANDATORY) used in `run_tests_local`
# GTEST_FILTER=$4 (optional) used in `run_tests_local`
# *** See `run_tests_local` for the args forwarded to that script

shift # arg1 (num transcripts) is not forwarded to `run_tests_local`

# END ARGS
###############################################################################

$(aws ecr get-login --region us-east-2 --no-include-email) 2> /dev/null

REPOSITORY="circuits-$ARCH-linux-clang-assert"
IMAGE_URI=$($(git rev-parse --show-toplevel)/build-system/scripts/calculate_image_uri $REPOSITORY)
$(git rev-parse --show-toplevel)/build-system/scripts/retry docker pull $IMAGE_URI

# run tests in docker image
RUN_ARGS="$@" # helper var necessary for some reason to pass all args to docker run
time docker run --rm -t $IMAGE_URI /bin/sh -c "\
  set -xe; \
  cd /usr/src/circuits/cpp/barretenberg/cpp/srs_db; \
  ln -sf /usr/src/circuits/cpp/barretenberg/cpp/srs_db /usr/src/circuits/cpp/srs_db; \
  ./download_ignition.sh $NUM_TRANSCRIPTS; \
  cd /usr/src/circuits/cpp; \
  export PATH=\$PATH:~/.wasmtime/bin/; \
  ./scripts/run_tests_local $RUN_ARGS;"
