// docs:start:oracles-module
/// Oracles module
// docs:end:oracles-module

mod arguments;
mod call_private_function;
mod context;
mod debug_log;
mod get_l1_to_l2_message;
mod get_nullifier_membership_witness;
mod get_public_data_witness;
mod get_membership_witness;
mod get_public_key;
mod nullifier_key;
mod get_sibling_path;
mod rand;
mod enqueue_public_function_call;
mod get_block_header;
mod public_call;
mod notes;
mod storage;
mod logs;
