FROM aztecprotocol/noir AS noir
FROM --platform=linux/amd64 aztecprotocol/bb.js as bb.js
FROM --platform=linux/amd64 aztecprotocol/noir-packages as noir-packages

FROM node:20 AS builder
COPY --from=bb.js /usr/src/barretenberg/ts /usr/src/barretenberg/ts
COPY --from=noir-packages /usr/src/noir/packages /usr/src/noir/packages

WORKDIR /usr/src/barretenberg/ts
RUN yarn --immutable

# Set the nargo backend to use the local bb.js of breaking serialization changes
# We use the backend to write the verification key for smart contract integration tests 
ENV NARGO_BACKEND_PATH=/usr/src/barretenberg/ts/dest/node/main.js

COPY --from=noir /usr/src/noir/noir-repo/target/release /usr/src/noir/noir-repo/target/release
ENV PATH=${PATH}:/usr/src/noir/noir-repo/target/release
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc
ENV PATH=/root/.cargo/bin:${PATH}
RUN apt update && apt install -y jq libc++1
ARG COMMIT_HASH
ENV COMMIT_HASH=${COMMIT_HASH}

WORKDIR /usr/src/noir
COPY . .
RUN ./scripts/test_js_packages.sh

# Don't waste time pushing a huge container back to ECR as nothing needs the output.
FROM scratch
COPY --from=builder /usr/src/noir/README.md /usr/src/noir/README.md