FROM rust:bullseye
ARG COMMIT_HASH
ENV COMMIT_HASH=${COMMIT_HASH}
RUN apt update && apt install -y libc++1
WORKDIR /usr/src/noir
COPY . .
RUN ./scripts/test_native.sh

# Don't waste time pushing a huge container back to ECR as nothing needs the output.
FROM scratch
COPY --from=0 /usr/src/noir/README.md /usr/src/noir/README.md