FROM aztecprotocol/noir AS noir

FROM node:20 AS builder
COPY --from=noir /usr/src/noir/noir-repo/target/release /usr/src/noir/noir-repo/target/release
ENV PATH=${PATH}:/usr/src/noir/noir-repo/target/release
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc
ENV PATH=/root/.cargo/bin:${PATH}
RUN apt update && apt install -y jq libc++1
ARG COMMIT_HASH
ENV COMMIT_HASH=${COMMIT_HASH}

WORKDIR /usr/src/noir
COPY . .
RUN ./scripts/test_js_packages.sh

# Don't waste time pushing a huge container back to ECR as nothing needs the output.
FROM scratch
COPY --from=builder /usr/src/noir/README.md /usr/src/noir/README.md