VERSION 0.8

nargo:
    FROM rust:bullseye
    RUN apt update && apt install -y libc++1
    WORKDIR /usr/src
    # Relevant source (TODO finer-grained 'tooling')
    COPY --dir \
      noir-repo/acvm-repo \
      noir-repo/aztec_macros \
      noir-repo/compiler \
      noir-repo/noir_stdlib \
      noir-repo/tooling \
      noir-repo/test_programs \
      noir-repo/Cargo.lock \
      noir-repo/Cargo.toml \
      noir-repo

    # TODO(AD) is this OK as a content hash?
    ENV COMMIT_HASH=$(find . -type f -exec sha256sum {} ';' | sort | sha256sum | awk '{print $1}')
    COPY ./scripts/bootstrap_native.sh ./scripts/bootstrap_native.sh
    RUN ./scripts/bootstrap_native.sh
    RUN echo CONTENT HASH $COMMIT_HASH | tee .content-hash
    SAVE ARTIFACT /usr/src/noir-repo/target/release/nargo nargo
    SAVE ARTIFACT /usr/src/noir-repo/target/release/acvm acvm
    SAVE IMAGE aztecprotocol/nargo

packages:
    FROM node:20

    RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
    RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc
    RUN apt update && apt install -y jq libc++1

    # `noir-repo` is nested inside of `noir` so we copy `bb.js` as such to account 
    # for the extra nested folder specified in portalled package paths
    COPY ../barretenberg/ts/+build/build /usr/src/../barretenberg/ts

    WORKDIR /usr/src

    # Relevant source (TODO finer-grained)
    COPY --dir \
      noir-repo/acvm-repo \
      noir-repo/aztec_macros \
      noir-repo/compiler \
      noir-repo/docs \
      noir-repo/noir_stdlib \
      noir-repo/scripts \
      noir-repo/test_programs \
      noir-repo/tooling \
      noir-repo/Cargo.lock \
      noir-repo/.yarnrc.yml \
      noir-repo/.yarn \
      noir-repo/yarn.lock \
      noir-repo/package.json \
      noir-repo/LICENSE* \
      noir-repo/*.toml \
      noir-repo/*.json \
      noir-repo/*.js \
      noir-repo/.github \
      noir-repo/.envrc \
      noir-repo

    COPY noir-repo/.github/scripts noir-repo/.github/scripts
    COPY ./scripts/bootstrap_packages.sh ./scripts/bootstrap_packages.sh

    # TODO(AD) is this OK as a content hash?
    ENV COMMIT_HASH=$(find . -type f -exec sha256sum {} ';' | sort | sha256sum | awk '{print $1}')
    RUN echo CONTENT HASH $COMMIT_HASH | tee .content-hash
    RUN PATH="/root/.cargo/bin:$PATH" ./scripts/bootstrap_packages.sh
    SAVE ARTIFACT packages
    SAVE IMAGE --cache-hint

run:
    # When running the container, mount the users home directory to same location.
    FROM ubuntu:lunar
    # Install Tini as nargo doesn't handle signals properly.
    # Install git as nargo needs it to clone.
    RUN apt-get update && apt-get install -y git tini && rm -rf /var/lib/apt/lists/* && apt-get clean
    COPY +build/. /usr/src
    ENTRYPOINT ["/usr/bin/tini", "--", "/usr/src/nargo"]

build:
  BUILD +nargo
  BUILD +packages

# TOOD
# test-packages
# FROM aztecprotocol/noir AS noir

# FROM node:20 AS builder
# COPY --from=noir /usr/src/noir/noir-repo/target/release /usr/src/noir/noir-repo/target/release
# ENV PATH=${PATH}:/usr/src/noir/noir-repo/target/release
# RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
# RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc
# ENV PATH=/root/.cargo/bin:${PATH}
# RUN apt update && apt install -y jq libc++1
# ARG COMMIT_HASH
# ENV COMMIT_HASH=${COMMIT_HASH}

# WORKDIR /usr/src/noir
# COPY . .
# RUN ./scripts/test_js_packages.sh

# # Don't waste time pushing a huge container back to ECR as nothing needs the output.
# FROM scratch
# COPY --from=builder /usr/src/noir/README.md /usr/src/noir/README.md

# TODO 
# test: 
# FROM rust:bullseye
# ARG COMMIT_HASH
# ENV COMMIT_HASH=${COMMIT_HASH}
# RUN apt update && apt install -y libc++1
# WORKDIR /usr/src/noir
# COPY . .
# RUN ./scripts/test_native.sh

# # Don't waste time pushing a huge container back to ECR as nothing needs the output.
# FROM scratch
# COPY --from=0 /usr/src/noir/README.md /usr/src/noir/README.md
