#!/bin/bash
set -e

REPOSITORY=$1
shift
SPEC=$1
shift
DOCKERFILE=$(query_manifest dockerfile $REPOSITORY)

cd $(query_manifest buildDir $REPOSITORY)

LAST_SUCCESSFUL_COMMIT=$(last_successful_commit $REPOSITORY)
echo "Last successful commit: $LAST_SUCCESSFUL_COMMIT"

if check_rebuild "$LAST_SUCCESSFUL_COMMIT" $REPOSITORY; then
  spot_run_script $SPEC ../.circleci/remote_build/remote_build $REPOSITORY $@
else
  echo "No rebuild necessary. Retagging..."
  STAGES=$(cat $DOCKERFILE | sed -n -e 's/^FROM .* AS \(.*\)/\1/p')
  for STAGE in $STAGES; do
    tag_remote_image $REPOSITORY cache-$LAST_SUCCESSFUL_COMMIT-$STAGE cache-$COMMIT_HASH-$STAGE || true
  done
  tag_remote_image $REPOSITORY cache-$LAST_SUCCESSFUL_COMMIT cache-$COMMIT_HASH
fi