#!/bin/bash
# Erase the image tag associated with the last commit for the given repository.
# If TILL_COMMIT_HASH is given, erase tags going back in time until we reach TILL_COMMIT_HASH.

REPOSITORY=$1
TILL_COMMIT_HASH=$2

if [ -n "$3" ]; then
  TAG_POSTFIX=-$3
fi

for COMMIT_HASH in $(git log -n 50 --pretty=format:"%H"); do
  TAG=cache-${COMMIT_HASH}$TAG_POSTFIX
  if image_exists $REPOSITORY $TAG; then
    echo "Erasing image tag: $REPOSITORY:$TAG"
    aws ecr batch-delete-image --region=$ECR_REGION --repository-name $1 --image-ids imageTag=$TAG > /dev/null
    if [ -z "$TILL_COMMIT_HASH" -o "$COMMIT_HASH" = "$TILL_COMMIT_HASH" ]; then
      break
    fi
  fi
done