use serde::{Deserialize, Serialize};

// This represents a CodeTracer trace, as generated by `nargo trace`.
#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct TraceArtifact {}

impl TraceArtifact {
    pub fn new() -> TraceArtifact {
        TraceArtifact {}
    }
}
