FROM 278380418400.dkr.ecr.eu-west-2.amazonaws.com/aztec-sandbox-base AS builder

FROM node:18-alpine

COPY --from=builder /usr/src/ /usr/src/
WORKDIR /usr/src/yarn-project/aztec-sandbox

ENTRYPOINT ["yarn"]
CMD [ "start" ]
EXPOSE 8080