#!/usr/bin/env bash
set -e

echo Installing nargoup...

NARGO_DIR=${NARGO_DIR-"$HOME/.nargo"}
NARGO_BIN_DIR="$NARGO_DIR/bin"

BIN_URL="https://raw.githubusercontent.com/noir-lang/noir/master/nargoup/nargoup"
BIN_PATH="$NARGO_BIN_DIR/nargoup"

# Create the .nargo bin directory and nargoup binary if it doesn't exist.
mkdir -p $NARGO_BIN_DIR
curl -# -L $BIN_URL -o $BIN_PATH
chmod +x $BIN_PATH

# Store the correct profile file (i.e. .profile for bash or .zshrc for ZSH).
case $SHELL in
*/zsh)
  PROFILE=$HOME/.zshrc
  PREF_SHELL=zsh
  ;;
*/bash)
  PROFILE=$HOME/.bashrc
  PREF_SHELL=bash
  ;;
*/fish)
  PROFILE=$HOME/.config/fish/config.fish
  PREF_SHELL=fish
  ;;
*/ash)
  PROFILE=$HOME/.profile
  PREF_SHELL=ash
  ;;
*)
  echo "nargoup: could not detect shell, manually add ${NARGO_BIN_DIR} to your PATH."
  exit 1
  ;;
esac

# Only add nargoup if it isn't already in PATH.
if [[ ":$PATH:" != *":${NARGO_BIN_DIR}:"* ]]; then
  # Add the nargoup directory to the path and ensure the old PATH variables remain.
  echo >>$PROFILE && echo "export PATH=\"\$PATH:$NARGO_BIN_DIR\"" >>$PROFILE
fi

echo && echo "Detected your preferred shell is ${PREF_SHELL} and added nargoup to PATH. Run 'source ${PROFILE}' or start a new terminal session to use nargoup."
echo "Then, simply run 'nargoup' to install Nargo."
