#!/bin/bash
# Runs a test script on a remote spot instance. Arguments are:
# 1. NAME: A unique short name given to this test run. The remote is tagged using this name to indicate success.
# 2. RUN_SCRIPT: The name of the script to copy and run on the remote instance.
# 3. COMMIT_HASH: The commit hash that triggered this build. Used in image location and tagging.
# 4... ARGS: Additional arguments specific to RUN_SCRIPT.
set -e

NAME=$1
COMMIT_HASH=$2

# Get spot instance.
IP=$(request_spot $COMMIT_HASH:$NAME)

# Run tests remotely on spot instance, capturing success or failure.
set +e
./remote_run_tests $IP $@
CODE=$?

# Shutdown spot.
echo "Terminating spot instance..."
ssh -F $SSH_CONFIG_PATH $IP sudo halt -p > /dev/null 2>&1

exit $CODE