FROM ubuntu:lunar as builder

RUN apt update && apt install -y \
  build-essential \
  curl \
  git \
  cmake \
  lsb-release \
  wget \
  software-properties-common \
  gnupg \
  ninja-build \
  npm \
  libssl-dev \
  jq \
  bash \
  libstdc++6

RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 16

WORKDIR /usr/src/barretenberg/cpp
COPY . .
# Build the entire project, as we want to check everything builds under clang-fuzzing with clang-16.
RUN cmake --preset fuzzing && cmake --build --preset fuzzing

FROM ubuntu:lunar
RUN apt update && apt install libomp-dev -y
COPY --from=builder /usr/src/barretenberg/cpp/srs_db /usr/src/barretenberg/cpp/srs_db
