#!/bin/bash
set -e

NUM_TRANSCRIPTS=$1
TESTS=$2
shift
shift
if [ -n "$3" ]; then
  WASM_MODE=$3
  shift
fi

$(aws ecr get-login --region us-east-2 --no-include-email) 2> /dev/null

IMAGE_URI=278380418400.dkr.ecr.us-east-2.amazonaws.com/aztec3-circuits-x86_64-linux-clang-assert:cache-$COMMIT_HASH

docker pull $IMAGE_URI

if [ -f "$TESTS" ]; then
  TESTS=$(cat $TESTS | tr '\n' ' ')
fi

if [ -z "$WASM_MODE" ]; then
  TEST_CMD="./bin/\$BIN $@"
else
  TEST_CMD="wasmtime --dir .. bin/\$BIN $@"
fi

docker run --rm -t $IMAGE_URI /bin/sh -c "\
  set -e; \
  cd /usr/src/aztec3-circuits/barretenberg/cpp/srs_db; \
  ./download_ignition.sh $NUM_TRANSCRIPTS; \
  ./download_ignition_lagrange.sh 24; \
  cd /usr/src/aztec3-circuits/build; \
  for BIN in $TESTS; do $TEST_CMD; done"
