#!/bin/bash
# This is the default test runner which takes the as arguments:
# 1. The number of ignition transcripts to download.
# 2. The set of gtest binary names to run.
# 3-n. The arguments to pass to the gtest binaries.
set -exu

NUM_TRANSCRIPTS=$1
TESTS=$2
shift
shift

$(aws ecr get-login --region us-east-2 --no-include-email) 2> /dev/null

# use the image rebuild patterns to compute a content hash, use this to get a URI
REPOSITORY=barretenberg-x86_64-linux-clang-assert
export PATH="$PATH:$(git rev-parse --show-toplevel)/build-system/scripts"
IMAGE_URI=$(calculate_image_uri $REPOSITORY)
retry docker pull $IMAGE_URI

if [ -f "$TESTS" ]; then
  TESTS=$(cat $TESTS | tr '\n' ' ')
fi

docker run --rm -t $IMAGE_URI /bin/sh -c "\
  set -xe; \
  cd /usr/src/barretenberg/cpp/srs_db; \
  ./download_ignition.sh $NUM_TRANSCRIPTS; \
  cd /usr/src/barretenberg/cpp/build; \
  ./bin/grumpkin_srs_gen 1048576; \
  for BIN in $TESTS; do ./bin/\$BIN $@; done"
