#!/bin/bash
set -e

NUM_TRANSCRIPTS=$1
TESTS=$2
shift
shift

$(aws ecr get-login --region us-east-2 --no-include-email) 2> /dev/null

IMAGE_URI=278380418400.dkr.ecr.us-east-2.amazonaws.com/barretenberg-x86_64-linux-clang-assert:cache-$COMMIT_HASH

docker pull $IMAGE_URI

if [ -f "$TESTS" ]; then
  TESTS=$(cat $TESTS | tr '\n' ' ')
fi

docker run --rm -t $IMAGE_URI /bin/sh -c "\
  set -e; \
  cd /usr/src/barretenberg/cpp/srs_db; \
  ./download_ignition.sh $NUM_TRANSCRIPTS; \
  ./download_ignition_lagrange.sh 12; \
  cd /usr/src/barretenberg/cpp/build; \
  for BIN in $TESTS; do ./bin/\$BIN $@; done"
