#!/bin/bash
set -e

# To be called from CI for testing with docker and AWS.
# Can't be called locally unless AWS credentials are set up.
#
# Call from config.yml
# Example:
#   command: cond_spot_run_script circuits-wasm-linux-clang-assert 1 wasm scripts/a3-tests -*.skip*:*.circuit*

AZTEC_COMMIT=$1 # Aztec commit/branch to checkout (MANDATORY)
NUM_TRANSCRIPTS=$2 # integer (MANDATORY)
ARCH=$3 # x86_64 or wasm (MUST BE LOWERCASE) (MANDATORY) used in aztec's circuits `run_tests_local`
# TESTS=$4 (MANDATORY) used in aztec's circuits `run_tests_local` (test files rel to circuits/cpp)
# GTEST_FILTER=$5 (optional) used in aztec's circuits `run_tests_local`
# *** See `run_tests_local` for the args forwarded to that script
shift # arg1 (aztec commit) and arg2 (num transcripts) are not forwarded
shift # to aztec's circuits `run_tests_local`

$(aws ecr get-login --region us-east-2 --no-include-email) 2> /dev/null

IMAGE_URI=278380418400.dkr.ecr.us-east-2.amazonaws.com/barretenberg-circuits-${ARCH}-linux-clang-builder-runner:cache-$COMMIT_HASH
docker pull $IMAGE_URI

if [ "$ARCH" != "wasm" ]; then
  # x86_64 / anything other than wasm
  PRESET=default
  CONFIGURE_OPTS="-DCMAKE_BUILD_TYPE=RelWithAssert -DCI=ON"
  BUILD_DIR=build
else
  PRESET=wasm
  BUILD_DIR=build-wasm
fi

echo "*** Running Aztec circuits tests on commit: $AZTEC_COMMIT"
# run tests in docker
RUN_ARGS="$@" # helper var necessary for some reason to pass all args to docker run
docker run --rm -t $IMAGE_URI /bin/sh -c "\
  set -e; \
  cd /usr/src/; \
  git clone https://github.com/AztecProtocol/aztec3-packages.git; \
  cd /usr/src/aztec3-packages/circuits/cpp; \
  git checkout $AZTEC_COMMIT; \
  rm -rf /usr/src/aztec3-packages/circuits/cpp/barretenberg;
  mv /usr/src/barretenberg .; \
  cmake --preset $PRESET $CONFIGURE_OPTS; \
  cmake --build --preset $PRESET; \
  cd /usr/src/aztec3-packages/circuits/cpp/barretenberg/cpp/srs_db; \
  ./download_ignition.sh $NUM_TRANSCRIPTS; \
  cd /usr/src/aztec3-packages/circuits/cpp; \
  export PATH=\$PATH:~/.wasmtime/bin/; \
  ./scripts/run_tests_local $RUN_ARGS;"
