#!/usr/bin/env bash
#
# Builds a docker image and pushes it to it's repository. Leverages caches where possible.
# Cached images include previous successfully built images (including multi-stages) built on this branch.
# The images output are cache images, meaning they will eventually get purged.
# The deploy phase will tag the images such that they become permanent.
#
# usage: ./build <repository>
# example: ./build aztec-connect-cpp-x86_64-linux-clang
# output image:
#   278380418400.dkr.ecr.us-east-2.amazonaws.com/aztec-connect-cpp-x86_64-linux-clang:cache-deadbeefcafebabe1337c0d3-x86_64
#
# In more detail:
# - Init all submodules required to build this project.
# - Log into cache ECR, and ensures repository exists.
# - Validate any terraform that may exist.
# - For images built previously in pipeline, pull the image we've built.
# - Perform the build of the image itself.
# - Push the image tagged with the content hash to the cache.

[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -euo pipefail

REPOSITORY=$1
DOCKERFILE=$(query_manifest dockerfile $REPOSITORY)
PROJECT_DIR=$(query_manifest projectDir $REPOSITORY)
BUILD_DIR=$(query_manifest buildDir $REPOSITORY)

echo "Repository: $REPOSITORY"
echo "Working directory: $PWD"
echo "Dockerfile: $DOCKERFILE"
echo "Build directory: $BUILD_DIR"

# Login to ECR and ensure repository exists.
retry ensure_repo $REPOSITORY $ECR_REGION refresh_lifecycle
# Login to dockerhub.
retry dockerhub_login

CONTENT_HASH=$(calculate_content_hash $REPOSITORY)
echo "Content hash: $CONTENT_HASH"

cd $BUILD_DIR

# If we have previously successful commit, we can early out if nothing relevant has changed since.
IMAGE_COMMIT_TAG=$(calculate_image_tag $REPOSITORY)
if check_rebuild $IMAGE_COMMIT_TAG $REPOSITORY; then
  echo "No rebuild necessary."
  exit 0
fi

echo "Initializing submodules..."
init_submodules $REPOSITORY

# Validate any terraform if it exists.
if [ -d $ROOT_PATH/$PROJECT_DIR/terraform ]; then
  echo "Checking terraform..."
  ensure_terraform
  export TF_IN_AUTOMATION=1
  pushd $ROOT_PATH/$PROJECT_DIR/terraform
  for DIR in . $(find . -maxdepth 1 -type d); do
    pushd $DIR
    if [ -f ./main.tf ]; then
      terraform init -input=false -backend-config="key=dummy"
      terraform validate
    fi
    popd
  done
  popd
fi

# For each dependency, substitute references to the dependency in dockerfile, with the relevent built image uri.
# This is necessary vs pulling and retagging the image, as that doesn't work with buildx.
# We have to perform a bit of probing to determine which actual image we want to use.
# When we used buildx to create a multiarch image, there will be no images with "-$ARCH" suffixes (normalise this?).
# Also we sometimes build an arm image from an x86 parent, so there won't always be an arm parent, and we fallback.
for PARENT_REPO in $(query_manifest dependencies $REPOSITORY); do
  # We want the parent image tag without any arch suffix.
  PARENT_IMAGE_TAG=$(calculate_image_tag $PARENT_REPO "")

  # Attempt to locate multiarch image.
  if ! image_exists $PARENT_REPO $PARENT_IMAGE_TAG; then
    # Attempt to locate our specific arch image.
    PARENT_IMAGE_TAG=$(calculate_image_tag $PARENT_REPO)
    if ! image_exists $PARENT_REPO $PARENT_IMAGE_TAG; then
      # Finally attempt to locate x86_64 image tag, as sometimes we build arch specific images from x86_64 images.
      PARENT_IMAGE_TAG=$(calculate_image_tag $PARENT_REPO x86_64)
      if ! image_exists $PARENT_REPO $PARENT_IMAGE_TAG; then
        echo "Failed to locate multiarch image, arch specific image, or x86_64 image for $PARENT_REPO. Aborting."
        exit 1
      fi
    fi
  fi

  # Substitute references to parent repo, with the relevent built image uri.
  DEPLOY_URI=aztecprotocol/$PARENT_REPO
  PARENT_IMAGE_URI=$ECR_URL/$PARENT_REPO:$PARENT_IMAGE_TAG
  sed -i "s#^FROM \\(.*\\)${DEPLOY_URI}\\( \|$\\)#FROM \\1${PARENT_IMAGE_URI}\\2#" $DOCKERFILE
done

# Build a dockerignore file that only permits git files and untracked files.
create_dockerignore $REPOSITORY

COMMIT_TAG_VERSION=$(extract_tag_version $REPOSITORY false)
echo "Commit tag version: $COMMIT_TAG_VERSION"

IMAGE_COMMIT_URI=$(calculate_image_uri $REPOSITORY)
echo "Building image: $IMAGE_COMMIT_URI"

MULTIARCH=$(query_manifest multiarch $REPOSITORY)

# Build the image.
if [ "$MULTIARCH" == "buildx" ]; then
  # We've requested to use buildx. This will build both arch containers on the host machine using virtualization.
  # The result is a single image tag that supports multiarch.
  # This is the simplest approach for build jobs that are not too intensive.
  docker buildx create --name builder --use
  docker buildx inspect --bootstrap
  docker buildx build -t $IMAGE_COMMIT_URI -f $DOCKERFILE --build-arg COMMIT_TAG=$COMMIT_TAG_VERSION --build-arg CONTENT_HASH=$CONTENT_HASH --build-arg COMMIT_HASH=$COMMIT_HASH --platform linux/amd64,linux/arm64 . --push
else
  # If multiarch is set to "host", the assumption is that we're doing multiple builds on different machine architectures
  # in parallel, and that there is a another job that runs afterwards to combine them into a manifest.
  # In this case we need to augment the image tag with the hosts architecture to ensure its uniqueness.
  if [ "$MULTIARCH" == "host" ]; then
    IMAGE_COMMIT_URI=$(calculate_image_uri $REPOSITORY host)
  fi

  docker build -t $IMAGE_COMMIT_URI -f $DOCKERFILE --build-arg COMMIT_TAG=$COMMIT_TAG_VERSION --build-arg CONTENT_HASH=$CONTENT_HASH --build-arg COMMIT_HASH=$COMMIT_HASH .
  echo "Pushing image: $IMAGE_COMMIT_URI"
  retry docker push $IMAGE_COMMIT_URI > /dev/null 2>&1
fi
