#!/bin/bash
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

REPOSITORY=$1
ARCH=${2:-$(uname -m)}
[ "$ARCH" == "aarch64" ] && ARCH=arm64
CONTENT_HASH=$(calculate_content_hash $REPOSITORY)
echo "cache-$CONTENT_HASH-$ARCH"
