#!/bin/bash
# If this script fails (nonzero exit), then the caller should rebuild.
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -euo pipefail

TAG=$1
REPOSITORY=$2

# If given nothing, then exit with failure to rebuild
[ -n "$TAG" ] || exit 1

if ! image_exists $REPOSITORY $TAG; then
  echo "Rebuild required."
  exit 1
elif image_exists $REPOSITORY tainted; then
  # If a tainted tag exists, remove it and exit with failure to rebuild.
  echo "$REPOSITORY has been tainted. Will rebuild."
  exit 1
else
  echo "No rebuild required."
  exit 0
fi
