#!/usr/bin/env bash
# If this script fails (nonzero exit), then the working copy is not clean.

[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

REPOSITORY=$1

# Get list of rebuild patterns, concat them with regex 'or' (|), and double escape \ for awk -v.
AWK_PATTERN=$(query_manifest rebuildPatterns $REPOSITORY | tr '\n' '|' | sed 's/\\/\\\\/g')
# Remove the trailing '|'.
AWK_PATTERN=${AWK_PATTERN%|}

cd "$(git rev-parse --show-toplevel)"

# Check if there is anything dirty in the local copy, if so, bail with non-zero exit code.
CHANGED_FILES=$(git status --porcelain | awk -v pattern="($AWK_PATTERN)" '$2 ~ pattern {print $2}')
if [ -n "$CHANGED_FILES" ]; then
  echo $CHANGED_FILES
  exit 1
fi