#!/bin/bash
# Conditionally runs a script on a remote spot instance if the REPOSITORY content hash has changed and we haven't had a
# successful run.
# The TAG_POSTFIX is used by cond_spot_run_test whereby we use an image tag postfixed with JOB_NAME to identifify if
# we need to re-run the job due to prior failures.
#
# Arguments are:
# 1. REPOSITORY: The project repository name in ECR. Used to determine if there are changes since last success.
# 2. CPUS: Number of cpus on spot request.
# 3... ARGS: Script and arguments to run.
#
# Env vars are:
# TAG_POSTFIX: Optional. If provided we check for the image tag with this postfix to determine if re-run is required.
set -eu

REPOSITORY=$1
CPUS=$2
shift 2

CONTENT_HASH=$(calculate_content_hash $REPOSITORY)
BASE_TAG=cache-$CONTENT_HASH
SUCCESS_TAG=$BASE_TAG

if [ -n "${TAG_POSTFIX:-}" ]; then
  SUCCESS_TAG=$BASE_TAG-$TAG_POSTFIX
fi

echo "Content hash: $CONTENT_HASH"

if ! check_rebuild $SUCCESS_TAG $REPOSITORY; then
  init_submodules $REPOSITORY
  spot_run_script $CONTENT_HASH $CPUS $@
  retry tag_remote_image $REPOSITORY $BASE_TAG $SUCCESS_TAG
fi
