#!/bin/bash
# This script:
# 1. Logs into DockerHub
# 2. Creates 2 manifest lists, the first is version tagged, the second is 'latest' tagged
# 3. Adds the arch specific tagged image to each list
# 4. Pushes the 2 lists

[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

if [ -z "$COMMIT_TAG" ]; then
  echo "Will only push tagged builds to dockerhub. Skipping."
  exit 0
fi

REPOSITORY=$1
ARCH_LIST=$2

echo "Repo: $REPOSITORY"
echo "Arch list: $ARCH_LIST"

ACCOUNT="aztecprotocol"
USERNAME="aztecprotocolci"

# Extract the version, if valid; exit otherwise.
IMAGE_TAG=$(extract_tag_version $REPOSITORY true)

MANIFEST_DEPLOY_URI=$ACCOUNT/$REPOSITORY:$IMAGE_TAG
MANIFEST_LATEST_URI=$ACCOUNT/$REPOSITORY:latest

# Login to dockerhub.
dockerhub_login

export DOCKER_CLI_EXPERIMENTAL=enabled

OLD_IFS=$IFS
IFS=','

# For each arch, add the tagged image to 2 manifest lists. One tagged with the version, the other with 'latest'
for A in $ARCH_LIST
do
  IMAGE_DEPLOY_URI=$ACCOUNT/$REPOSITORY:$IMAGE_TAG-$A
  echo "Adding image $IMAGE_DEPLOY_URI to manifest list $MANIFEST_DEPLOY_URI"
  docker_or_dryrun manifest create $MANIFEST_DEPLOY_URI \
  --amend $IMAGE_DEPLOY_URI
  
  echo "Adding image $IMAGE_DEPLOY_URI to manifest list $MANIFEST_LATEST_URI"
  docker_or_dryrun manifest create $MANIFEST_LATEST_URI \
  --amend $IMAGE_DEPLOY_URI
done

IFS=$OLD_IFS
unset OLD_IFS

echo "Pushing manifest list $MANIFEST_DEPLOY_URI..."
# Push the version tagged list
docker_or_dryrun manifest push --purge $MANIFEST_DEPLOY_URI

echo "Pushing manifest list $MANIFEST_LATEST_URI..."
# Push the latest tagged list
docker_or_dryrun manifest push --purge $MANIFEST_LATEST_URI
