#!/usr/bin/env bash
# This script:
# 1. Logs into ECR and ensures we have the given repository
# 2. Computes the image uri of the cached images for the given repository given the list of architectures
# 3. Creates a manifest list using a platform agnositc image uri, adds each image to it
# 4. Pushes the manifest list

[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

REPOSITORY=$1
ARCH_LIST=$2

retry ecr_login

CONTENT_HASH=$(calculate_content_hash $REPOSITORY)
MULTIARCH_IMAGE_URI=$ECR_URL/$REPOSITORY:cache-$CONTENT_HASH

echo "Multi-arch Image URI: $MULTIARCH_IMAGE_URI"

export DOCKER_CLI_EXPERIMENTAL=enabled

IFS=','
for A in $ARCH_LIST; do
  IMAGE_URI=$(calculate_image_uri $REPOSITORY $A)
  echo "Adding image $IMAGE_URI to manifest list $MULTIARCH_IMAGE_URI..."
  retry docker manifest create $MULTIARCH_IMAGE_URI --amend $IMAGE_URI
done

retry docker manifest push --purge $MULTIARCH_IMAGE_URI
