#!/bin/bash
# This script:
# 1. Logs into DockerHub
# 2. Creates 2 manifest lists, the first is version tagged, the second is 'latest' tagged
# 3. Adds the arch specific tagged image to each list
# 4. Pushes the 2 lists

set -eu

if [ -z "$COMMIT_TAG" ]; then
  echo "Will only push tagged builds to dockerhub. Skipping."
  exit 0
fi

REPOSITORY=$1
ARCH_LIST=$2

echo "Repo: $REPOSITORY"
echo "Arch list: $ARCH_LIST"

ACCOUNT="aztecprotocol"
USERNAME="aztecprotocolci"

COMMIT_TAG_VERSION=$COMMIT_TAG # default unless repo-specific
# Check if it's a repo-specific tag
if [[ "$COMMIT_TAG" == *"/"* ]]; then
  REPO_NAME="${COMMIT_TAG%%/*}"
  COMMIT_TAG_VERSION="${COMMIT_TAG#*/}"
  echo "Tag was made for: $REPO_NAME"
  echo "Version: $COMMIT_TAG_VERSION"

    # Check if REPO_NAME is equal to REPOSITORY
  if [ "$REPO_NAME" != "$REPOSITORY" ]; then
    echo "REPO_NAME ($REPO_NAME) does not match REPOSITORY ($REPOSITORY). Exiting..."
    exit 1
  fi
fi

# Check it's a valid semver.
VERSION=$(npx semver $COMMIT_TAG_VERSION)
if [ -z "$VERSION" ]; then
  echo "$COMMIT_TAG_VERSION is not a semantic version."
  exit 1
fi

# We now have the tage for each image
IMAGE_TAG=$COMMIT_TAG_VERSION

MANIFEST_DEPLOY_URI=$ACCOUNT/$REPOSITORY:$IMAGE_TAG
MANIFEST_LATEST_URI=$ACCOUNT/$REPOSITORY:latest

# Login to dockerhub.
echo "$DOCKERHUB_PASSWORD" | docker login -u $USERNAME --password-stdin

export DOCKER_CLI_EXPERIMENTAL=enabled

OLD_IFS=$IFS
IFS=','

# For each arch, add the tagged image to 2 manifest lists. One tagged with the version, the other with 'latest'
for A in $ARCH_LIST
do
  IMAGE_DEPLOY_URI=$ACCOUNT/$REPOSITORY:$IMAGE_TAG-$A
  echo "Adding image $IMAGE_DEPLOY_URI to manifest list $MANIFEST_DEPLOY_URI"
  docker manifest create $MANIFEST_DEPLOY_URI \
  --amend $IMAGE_DEPLOY_URI

  echo "Adding image $IMAGE_DEPLOY_URI to manifest list $MANIFEST_LATEST_URI"
  docker manifest create $MANIFEST_LATEST_URI \
  --amend $IMAGE_DEPLOY_URI
done

IFS=$OLD_IFS
unset OLD_IFS

echo "Pushing manifest list $MANIFEST_DEPLOY_URI..."
# Push the version tagged list
docker manifest push --purge $MANIFEST_DEPLOY_URI

echo "Pushing manifest list $MANIFEST_LATEST_URI..."
# Push the latest tagged list
docker manifest push --purge $MANIFEST_LATEST_URI