#!/bin/bash
set -eu

if [ -z "$COMMIT_TAG" ]; then
  echo "Will only push tagged builds to dockerhub. Skipping."
  exit 0
fi

REPOSITORY=$1
ARCH=${2:-""}

echo "Repo: $REPOSITORY"
echo "Arch: $ARCH"

ACCOUNT="aztecprotocol"
USERNAME="aztecprotocolci"

IMAGE_COMMIT_URI=$ECR_DEPLOY_URL/$REPOSITORY:$COMMIT_HASH

IMAGE_LATEST_URI=$ACCOUNT/$REPOSITORY:latest
if [[ -n "$ARCH" ]]; then
  IMAGE_COMMIT_URI=$IMAGE_COMMIT_URI-$ARCH
  IMAGE_LATEST_URI=$IMAGE_LATEST_URI-$ARCH
fi

COMMIT_TAG_VERSION=$(extract_tag_version $REPOSITORY "true")

IMAGE_TAG=$COMMIT_TAG_VERSION
IMAGE_DEPLOY_URI=$ACCOUNT/$REPOSITORY:$IMAGE_TAG
if [[ -n "$ARCH" ]]; then
  IMAGE_DEPLOY_URI=$IMAGE_DEPLOY_URI-$ARCH
fi

echo "Deploying to dockerhub: $IMAGE_DEPLOY_URI"

# Login.
retry ensure_repo $REPOSITORY $ECR_DEPLOY_REGION

function docker_login() {
  # Retries up to 3 times with 10 second intervals
  for i in $(seq 1 3); do
    echo "$DOCKERHUB_PASSWORD" | docker login -u $USERNAME --password-stdin && return || sleep 10
  done
  echo "$@ failed docker_login after 3 attempts"
  exit 1
}

# Login to dockerhub.
docker_login

echo "Pulling $IMAGE_COMMIT_URI"
# Pull image.
retry docker pull $IMAGE_COMMIT_URI

echo "Tagging $IMAGE_COMMIT_URI as $IMAGE_DEPLOY_URI"
# Tag with commit tag
retry docker tag $IMAGE_COMMIT_URI $IMAGE_DEPLOY_URI

echo "Tagging $IMAGE_COMMIT_URI as $IMAGE_LATEST_URI"
# Tag with :latest
retry docker tag $IMAGE_COMMIT_URI $IMAGE_LATEST_URI

# Push tagged image to dockerhub.
retry docker push $IMAGE_DEPLOY_URI
# Push :latest image to dockerhub
retry docker push $IMAGE_LATEST_URI
