#!/usr/bin/env bash
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

readonly REPOSITORY=$1
readonly DIST_TAG=${2:-"latest"}
readonly STANDALONE=${3:-}

# Only publish tagged commits to npm.
[ -n "${COMMIT_TAG:-}" ] || { echo "Will only publish tagged commits to npm. Skipping." && exit 0; }

retry ecr_login
extract_repo $REPOSITORY /usr/src project

cd project/src/$(query_manifest relativeProjectDir $REPOSITORY)

echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >.npmrc

VERSION=$(extract_tag_version $REPOSITORY true)
PACKAGE_NAME=$(jq -r '.name' package.json)

# If the commit tag itself has a dist-tag (e.g. v2.1.0-testnet.123), extract the dist-tag.
TAG=$(echo "$VERSION" | grep -oP ".*-\K(.*)(?=\.\d+)" || true)
TAG_ARG=""
if [ -n "$TAG" ]; then
  TAG_ARG="--tag $TAG"
else
  TAG_ARG="--tag $DIST_TAG"
  TAG=$DIST_TAG
fi

readonly PUBLISHED_VERSION=$(npm show . version ${TAG_ARG:-} 2>/dev/null)
readonly HIGHER_VERSION=$(npx semver ${VERSION} ${PUBLISHED_VERSION} | tail -1)

# If there is already a published package equal to given version, assume this is a re-run of a deploy, and early out.
if [ "$VERSION" == "$PUBLISHED_VERSION" ]; then
  echo "Tagged ${DIST_TAG:+ $DIST_TAG}version $VERSION is equal to published ${DIST_TAG:+ $DIST_TAG}version $PUBLISHED_VERSION. Skipping publish."
  exit 0
fi

# If the published version is > the given version, something's gone wrong.
if [ "$VERSION" != "$HIGHER_VERSION" ]; then
  echo "Tagged version $VERSION is lower than published version $PUBLISHED_VERSION."
  exit 1
fi

# Update the package version in package.json.
TMP=$(mktemp)
jq --arg v $VERSION '.version = $v' package.json >$TMP && mv $TMP package.json

if [ -z "$STANDALONE" ]; then
  # Update each dependent @aztec package version in package.json.
  for PKG in $(jq --raw-output ".dependencies | try keys[] | select(contains(\"@aztec/\"))" package.json); do
    jq --arg v $VERSION ".dependencies[\"$PKG\"] = \$v" package.json >$TMP && mv $TMP package.json
  done
fi

# Publish if we have a commit tag
if [ "$DRY_DEPLOY" -eq 1 ]; then
  npm publish --dry-run $TAG_ARG --access public
else
  # npm publish $TAG_ARG --access public
  # Check if version exists
  if npm view "$PACKAGE_NAME@$VERSION" version >/dev/null 2>&1; then
    # Tag the existing version
    echo "Tagging existing version $VERSION with $TAG"
    npm dist-tag add $PACKAGE_NAME@$VERSION $TAG
  else
    # Publish new version
    echo "Publishing new version $VERSION with $TAG"
    npm publish $TAG_ARG --access public
  fi
fi
