#!/bin/bash
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

REPOSITORY=$1
# TODO: Why even provide this? We can just figure it out by probing.
ARCH_LIST=${2:-}

# The tag to use for release images. Can be turned into an argument if needed, for now we only release 'latest'.
DIST_TAG="latest"

function docker_or_dryrun {
  if [ "$DRY_DEPLOY" -eq 1 ]; then
    echo DRY RUN: docker $@
  else
    retry docker $@
  fi
}

echo "Repo: $REPOSITORY"
echo "Arch List: $ARCH_LIST"

VERSION_TAG=$(extract_tag_version $REPOSITORY false)

# if no version tag, check if we're on `master` branch
if [[ -z "$VERSION_TAG" ]]; then
  if [[ "$BRANCH" != "master" ]]; then
    echo "No version tag found. Exiting" >&2
    exit 1
  fi
  # if we're on master, use the DEPLOY_TAG as the version tag
  VERSION_TAG=$DEPLOY_TAG
fi

MANIFEST_DEPLOY_URI=$DOCKERHUB_ACCOUNT/$REPOSITORY:$VERSION_TAG
MANIFEST_DIST_URI=$DOCKERHUB_ACCOUNT/$REPOSITORY:$DIST_TAG

# Login to dockerhub and ecr
dockerhub_login
ecr_login

IFS=','
for ARCH in $ARCH_LIST; do
  IMAGE_COMMIT_URI=$(calculate_image_uri $REPOSITORY $ARCH)
  retry docker pull $IMAGE_COMMIT_URI

  # Retag and push image.
  IMAGE_DEPLOY_URI=$DOCKERHUB_ACCOUNT/$REPOSITORY:$VERSION_TAG-$ARCH
  docker tag $IMAGE_COMMIT_URI $IMAGE_DEPLOY_URI
  docker_or_dryrun push $IMAGE_DEPLOY_URI

  echo "Adding image $IMAGE_DEPLOY_URI to manifest list $MANIFEST_DEPLOY_URI..."
  docker_or_dryrun manifest create $MANIFEST_DEPLOY_URI --amend $IMAGE_DEPLOY_URI

  # Add latest manifest if we're making a release.
  if [[ "$VERSION_TAG" != $DEPLOY_TAG ]]; then
    echo "Adding image $IMAGE_DEPLOY_URI to manifest list $MANIFEST_DIST_URI"
    docker_or_dryrun manifest create $MANIFEST_DIST_URI --amend $IMAGE_DEPLOY_URI
  fi
done

docker_or_dryrun manifest push --purge $MANIFEST_DEPLOY_URI

# Retag version as latest if we're making a release.
if [[ "$VERSION_TAG" != "$DEPLOY_TAG" ]]; then
  echo "Tagging $MANIFEST_DEPLOY_URI as $DIST_TAG..."
  docker_or_dryrun manifest push --purge $MANIFEST_DIST_URI
fi
