#!/bin/bash
# Deployment script for global service (e.g. company website and metrics).
set -eu

REPOSITORY=$1

cd $(query_manifest projectDir $REPOSITORY)

# Regardless of whether the repo changed or not, we want to update tags in the deployment repo.
deploy_ecr $REPOSITORY

# Bail out if nothing changed.
CONTENT_HASH=$(calculate_content_hash $REPOSITORY)
echo "Last successfully deployed commit: $CONTENT_HASH"
if check_rebuild cache-$CONTENT_HASH-$DEPLOY_TAG-deployed $REPOSITORY; then
  echo "No changes detected, skipping deployment."
  exit 0
fi

deploy_terraform "" ./terraform

deploy_service $REPOSITORY

# Tag the image as deployed.
tag_remote_image $REPOSITORY cache-$CONTENT_HASH cache-$CONTENT_HASH-$DEPLOY_TAG-deployed
