#!/bin/bash
set -eu
REGION=${1:-$ECR_REGION}
# Retries up to 3 times with 10 second intervals
for i in $(seq 1 3); do
  aws ecr get-login-password --region $REGION \
    | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$REGION.amazonaws.com 2> /dev/null \
    && exit || sleep 10
done
echo "$@ failed ecr_login after 3 attempts"
exit 1
