#!/bin/bash
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

if dpkg -s $1 &> /dev/null; then
  exit 0
fi

>&2 echo "Installing $1..."
sudo apt update &> /dev/null && sudo apt install --force-yes $1 &> /dev/null
