#!/bin/bash
#
# This script forces a build if we're in a deployment run, otherwise runs `build` as usual
#
# usage: ./deploy_force_build <repository> <force-build>
# example: ./deploy_force_build aztec-sandbox true
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -e

REPOSITORY=$1
shift
FORCE_BUILD=$1
shift

# if FORCE_BUILD is already set, just continue with it
if [[ $FORCE_BUILD == 'true' ]]; then
  build $REPOSITORY true $@
  exit 0
fi

COMMIT_TAG_VERSION=$(extract_tag_version $REPOSITORY "false")

if [ -z "$COMMIT_TAG_VERSION" ]; then
  # Not a version tag, build normally
  build $REPOSITORY false $@
else
  # Force build
  build $REPOSITORY true $@
fi
