#!/usr/bin/env bash
# Copies the runner script to the remote instance, runs it giving it script and args to run.
# The runner script checks out the repository first and runs setup-env.
#
# 1. IP: The IP address of the system to run the script on.
# 2... ARGS: Script and arguments to run.
#
# e.g. remote_run_script 1.2.3.4 build my_repo
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

IP=$1
shift

SSH_CONFIG_PATH=${SSH_CONFIG_PATH:-$BUILD_SYSTEM_PATH/remote/ssh_config}

# Copy the runner script to spot instance. This is what we actually run.
echo "Copying ./remote_initialize to $IP..."
scp -rF $SSH_CONFIG_PATH $BUILD_SYSTEM_PATH/scripts/remote_initialize $IP:.

# Run script on remote instance, passing environment variables.
echo "Running $@ on $IP..."
ssh -A -F $SSH_CONFIG_PATH $IP "
  export COMMIT_HASH=$COMMIT_HASH
  export COMMIT_TAG=$COMMIT_TAG
  export JOB_NAME=$JOB_NAME
  export GIT_REPOSITORY_URL=$GIT_REPOSITORY_URL
  export BRANCH=${BRANCH:-}
  export PULL_REQUEST=${PULL_REQUEST:-}
  export DOCKERHUB_PASSWORD=$DOCKERHUB_PASSWORD
  export ECR_URL=$ECR_URL
  export BUILD_SYSTEM_DEBUG=${BUILD_SYSTEM_DEBUG:-}

  # temp while we transitioning to avm
  export AVM_ENABLED=${AVM_ENABLED:-}
  source ./remote_initialize
  $@
"
