#!/bin/bash
# Copies the runner script to the remote instance, runs it giving it script and args to run.
# The runner script checks out the repository first and runs setup-env.
#
# 1. IP: The IP address of the system to run the script on.
# 2... ARGS: Script and arguments to run.
#
# e.g. remote_run_script 1.2.3.4 build my_repo
set -eu

IP=$1
shift

SSH_CONFIG_PATH=${SSH_CONFIG_PATH:-$BUILD_SYSTEM_PATH/remote/ssh_config}

# Copy the runner script to spot instance. This is what we actually run.
scp -rF $SSH_CONFIG_PATH $BUILD_SYSTEM_PATH/scripts/remote_runner $IP:.

# Run script on remote instance, passing environment variables.
echo "Running ./remote_runner $@ on $IP..."
ssh -A -F $SSH_CONFIG_PATH $IP "
  export COMMIT_HASH=$COMMIT_HASH
  export COMMIT_TAG=$COMMIT_TAG
  export JOB_NAME=$JOB_NAME
  export GIT_REPOSITORY_URL=$GIT_REPOSITORY_URL
  export DOCKERHUB_PASSWORD=$DOCKERHUB_PASSWORD
  export ECR_DEPLOY_URL=$ECR_DEPLOY_URL
  export ECR_URL=$ECR_URL
  ./remote_runner $@
"
