#!/usr/bin/env bash
# Returns success if we are expected to do a deployment.
# Right now, that's only if we're master.
set -eu

if [ "$BRANCH" == "master" ] || [ "$DRY_DEPLOY" -eq 1 ]; then
  exit 0
else
  exit 1
fi
