#!/bin/bash
set -eu
SCRIPT_PATH=$1
REPOSITORY=$2
shift
shift

cd $(query_manifest projectDir $REPOSITORY)

mkdir -p /tmp/test-logs

[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -o pipefail

CONTENT_HASH=$(calculate_content_hash $REPOSITORY)
echo "Content hash: $CONTENT_HASH"
spot_run_script $CONTENT_HASH 32 $SCRIPT_PATH $@ | tee "/tmp/test-logs/$JOB_NAME.log"
