#!/usr/bin/env bash
# Runs a test script on a remote spot instance. Arguments are:
# 1. NAME: Used to identify spot jobs.
# 2. CPUS: Number of cpus on spot request.
# 3... ARGS: Script and arguments to run.
#
# Env vars:
# JOB_NAME: Set within setup-env. The job name as per CI.
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu
REPOSITORY=$1
NAME=$2
CPUS=$3
ARCH=$4
shift 4
IP=

# On any sort of exit (error or not).
function on_exit {
    # We want to execute all this block, regardless of potential errors.
    set +e

    if [[ "$COMMIT_MESSAGE" == *"[ci no-term $REPOSITORY]"* ]]; then
        echo "Not terminating instance on request. You can connect with 'ssh -i build_instance_key ubuntu@$IP'"
        return
    fi

    if [ -n "$IP" ]; then
        echo "Terminating spot instance..."
        ssh -F $SSH_CONFIG_PATH $IP sudo halt -p > /dev/null 2>&1
    fi

    # Kill spot request so it doesn't count against quota.
    if [ -f "sir-$NAME.txt" ]; then
        SIR=$(cat sir-$NAME.txt)
        echo "Cancelling spot instance request $SIR..."
        aws ec2 cancel-spot-instance-requests --spot-instance-request-ids $SIR >/dev/null 2>&1 || true
    fi
}
trap on_exit EXIT

# Get spot instance.
IP=$(retry request_spot $NAME $CPUS $ARCH)

if [ -z "$IP" ]; then
    echo "Failed to get spot instance."
    exit 1
fi

# Run script remotely on spot instance, returning success or failure.
remote_run_script $IP $@