#!/usr/bin/env bash
# This is the default test runner which takes the as arguments:
# 1. The number of ignition transcripts to download.
# 2. The set of gtest binary names to run.
# 3-n. The arguments to pass to the gtest binaries.
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

NUM_TRANSCRIPTS=$1
TESTS=$2
shift
shift

$(aws ecr get-login --region us-east-2 --no-include-email) 2> /dev/null
# use the image rebuild patterns to compute a content hash, use this to get a URI
REPOSITORY=barretenberg-x86_64-linux-clang-assert

export PATH="$PATH:$(git rev-parse --show-toplevel)/build-system/scripts"
IMAGE_URI=$(calculate_image_uri $REPOSITORY)
retry docker pull $IMAGE_URI

# If there is a file in the scripts directory named $TESTS, those are the tests to run.
cd $(query_manifest projectDir $REPOSITORY)/scripts
if [ -f "$TESTS" ]; then
  TESTS=$(cat $TESTS | tr '\n' ' ')
fi

# Convert the string it an array so we can process as args to gtest-parallel
IFS=' ' read -r -a TEST_ARRAY <<< $TESTS
# Prepend ./bin/ and append any args (e.g. gTest Filters)
TESTS_STR="${TEST_ARRAY[@]/#/./bin/}"
TESTS_STR="${TESTS_STR[@]/%/ ${@}}"
docker run --rm -t $IMAGE_URI /bin/sh -c "\
  set -xe; \
  /usr/src/barretenberg/cpp/srs_db/download_ignition.sh $NUM_TRANSCRIPTS; \
  /usr/src/barretenberg/cpp/srs_db/download_grumpkin.sh; \
  cd /usr/src/barretenberg/cpp/build; \
  echo $TESTS_STR | xargs gtest-parallel/gtest-parallel --worker=32;"
