FROM aztecprotocol/crosstool-ng-arm64:latest
WORKDIR /usr/src/aztec3-circuits
COPY . .
RUN mkdir build && cd build && cmake -DTOOLCHAIN=arm64-linux-gcc .. && cmake --build . --parallel
RUN cd build && for test in ./bin/*_tests; do qemu-aarch64 $test; done
ENTRYPOINT /bin/bash