#!/bin/bash
# Conditionally runs a script if any dependent code has changed between
# the last successful run and the present commit.
#
# It's expected to be run from the project directory, and that there be a directory called `scripts`
# containing the given named script to execute.
#
# This script is only useful if there is nothing to do in the event there is no rebuild. This is fine
# for running a suite of tests for example, but is not useful for performing a build, as even if a
# build has nothing to do, the previous images are retagged with the new commit hash for upstream jobs.
#
# Arguments are:
# 1. REPOSITORY: The project repository name in ECR. Used to determine if there are changes since last success.
# 2. SUCCESS_TAG: To track if this job needs to be run, the repository image is tagged with a success tag after a
#    successful run. The script will only run if there were relevant code changes since the last successful commit.
# 3... ARGS: Script to run and args.
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

REPOSITORY=$1
shift
SUCCESS_TAG=$1
shift
SCRIPT_TO_RUN=$1
shift

CONTENT_HASH=$(calculate_content_hash $REPOSITORY)
echo "Content hash tag: cache-$CONTENT_HASH-$SUCCESS_TAG"
echo "Script to run is $SCRIPT_TO_RUN $@"

if ! check_rebuild cache-$CONTENT_HASH-$SUCCESS_TAG $REPOSITORY; then
  "$SCRIPT_TO_RUN" "$@"
  retry tag_remote_image $REPOSITORY cache-$CONTENT_HASH cache-$CONTENT_HASH-$SUCCESS_TAG
fi
