#!/bin/bash
# This script is used to run an e2e test in CI (see config.yml and cond_spot_run_tests).
# It sets a few environment variables used inside the docker-compose.yml, pulls images, and runs docker-compose.
set -eu

export TEST=$1
export IMAGE=${2:-canary}
export COMPOSE_FILE=${3:-./scripts/docker-compose.yml}

if [ "$TEST" = "uniswap_trade_on_l1_from_l2.test.ts" ]; then
  export FORK_URL=https://mainnet.infura.io/v3/9928b52099854248b3a096be07a6b23c
  export FORK_BLOCK_NUMBER=17514288
fi

aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 278380418400.dkr.ecr.us-east-2.amazonaws.com

IMAGE_URI=$($(git rev-parse --show-toplevel)/build-system/scripts/calculate_image_uri $IMAGE)
docker pull $IMAGE_URI
docker tag $IMAGE_URI aztecprotocol/canary:latest

SANDBOX_IMAGE_URI=$($(git rev-parse --show-toplevel)/build-system/scripts/calculate_image_uri aztec-sandbox)
docker pull $SANDBOX_IMAGE_URI
docker tag $SANDBOX_IMAGE_URI aztecprotocol/sandbox:latest

docker-compose -f $COMPOSE_FILE rm -f
docker-compose -f $COMPOSE_FILE up --exit-code-from canary
