#!/bin/bash
# This script is used to run an e2e test in CI (see config.yml and cond_spot_run_tests).
# It sets a few environment variables used inside the docker-compose.yml, pulls images, and runs docker-compose.
[ -n "${BUILD_SYSTEM_DEBUG:-}" ] && set -x # conditionally trace
set -eu

export TEST=$1
export IMAGE=${2:-canary}
export COMPOSE_FILE=${3:-./scripts/docker-compose.yml}
:
# if test name ends with uniswap_trade_on_l1_from_l2.test.ts, use the forked mainnet
if [[ "$TEST" == *"uniswap_trade_on_l1_from_l2"* ]]; then
  export FORK_URL=https://mainnet.infura.io/v3/9928b52099854248b3a096be07a6b23c
  export FORK_BLOCK_NUMBER=17514288
fi

# Login to ECR.
ecr_login

export PATH="$PATH:$(git rev-parse --show-toplevel)/build-system/scripts"
IMAGE_URI=$(calculate_image_uri $IMAGE)
retry docker pull $IMAGE_URI
retry docker tag $IMAGE_URI aztecprotocol/canary:latest

export SANDBOX_VERSION=canary
docker-compose -f ../../aztec-sandbox/docker-compose.yml -f $COMPOSE_FILE rm -f
docker-compose -f ../../aztec-sandbox/docker-compose.yml -f $COMPOSE_FILE up --exit-code-from canary
