VERSION 0.8
FROM ubuntu:lunar

# Install nargo
COPY ../noir/+nargo/nargo /usr/bin/nargo
# Install transpiler
COPY ../avm-transpiler/+build/avm-transpiler /usr/bin/avm-transpiler

WORKDIR /usr/src/noir-projects

# Copy source.
COPY --dir aztec-nr noir-contracts noir-protocol-circuits .

source:
  # for debugging rebuilds
  RUN echo CONTENT HASH $(find . -type f -exec sha256sum {} ';' | sort | sha256sum | awk '{print $1}') | tee .content-hash

build:
  FROM +source
  RUN apt-get update && apt-get install -y parallel
  RUN cd noir-contracts && NARGO=nargo TRANSPILER=avm-transpiler ./bootstrap.sh
  RUN cd noir-protocol-circuits && NARGO=nargo ./bootstrap.sh
  SAVE ARTIFACT aztec-nr
  SAVE ARTIFACT noir-contracts
  SAVE ARTIFACT noir-protocol-circuits

test:
  FROM +build
  RUN cd noir-protocol-circuits && nargo test --silence-warnings
  RUN cd aztec-nr && nargo test --silence-warnings
  RUN cd noir-contracts && nargo test --silence-warnings
