FROM 278380418400.dkr.ecr.eu-west-2.amazonaws.com/barretenberg-wasm-linux-clang as bb

FROM ubuntu:lunar AS builder
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git libssl-dev cmake ninja-build curl binaryen
COPY --from=bb /usr/src/barretenberg/cpp /usr/src/barretenberg/cpp
WORKDIR /usr/src/circuits/cpp
COPY . .
RUN cmake --preset wasm && cmake --build --preset wasm

FROM ubuntu:lunar
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y xz-utils curl
RUN curl https://wasmtime.dev/install.sh -sSf | bash /dev/stdin --version v3.0.1
COPY --from=builder /usr/src/barretenberg/cpp/srs_db /usr/src/barretenberg/cpp/srs_db
COPY --from=builder /usr/src/circuits/cpp/src/aztec3/circuits/kernel/private/fixtures /usr/src/circuits/cpp/src/aztec3/circuits/kernel/private/fixtures
COPY --from=builder /usr/src/circuits/cpp/scripts /usr/src/circuits/cpp/scripts
COPY --from=builder /usr/src/circuits/cpp/build-wasm/bin/*_tests /usr/src/circuits/cpp/build-wasm/bin/
