FROM 278380418400.dkr.ecr.eu-west-2.amazonaws.com/barretenberg-x86_64-linux-clang as bb

FROM alpine:3.17 AS builder
RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
        build-base \
        clang15 \
        clang15-extra-tools \
        openmp-dev \
        cmake \
        ninja \
        git \
        curl \
        perl \
        bash \
        python3
COPY --from=bb /usr/src/barretenberg/cpp /usr/src/barretenberg/cpp
WORKDIR /usr/src/circuits/cpp
COPY . .
# Configure cmake and check if code is tidy
RUN cmake --preset default
RUN ./scripts/tidy.sh fix