FROM alpine:3.17 AS builder
RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
        build-base \
        clang15 \
        openmp-dev \
        cmake \
        ninja \
        git \
        curl \
        perl

WORKDIR /usr/src/aztec3-circuits/cpp

COPY . .
# Build everything to ensure everything builds. All tests will be run from the result of this build.
RUN cmake --preset default -DCMAKE_BUILD_TYPE=RelWithAssert -DCI=ON && cmake --build --preset default

FROM alpine:3.17
RUN apk update && apk add curl openmp
COPY --from=builder /usr/src/aztec3-circuits/cpp/barretenberg/cpp/srs_db /usr/src/aztec3-circuits/cpp/barretenberg/cpp/srs_db
COPY --from=builder /usr/src/aztec3-circuits/cpp/build/bin/*_tests /usr/src/aztec3-circuits/cpp/build/bin/