VERSION 0.8

FROM ../../build-images+from-registry
WORKDIR /usr/src/barretenberg/ts-build

# minimum files to download yarn packages
# keep timestamps for incremental builds
COPY --dir .yarn package.json yarn.lock .yarnrc.yml .
RUN echo CONTENT HASH $(find . -type f -exec sha256sum {} ';' | sort | sha256sum | awk '{print $1}') | tee .content-hash
RUN yarn --immutable

# other source files
COPY --dir src *.json *.js *.cjs .

# copy over wasm builds from cpp folder
COPY ../cpp/+preset-wasm-threads/bin/barretenberg.wasm src/barretenberg_wasm/barretenberg-threads.wasm
COPY ../cpp/+preset-wasm/bin/barretenberg.wasm src/barretenberg_wasm/barretenberg.wasm
COPY ../cpp/+preset-wasm-threads/bin/barretenberg.wasm dest/node/barretenberg_wasm/barretenberg-threads.wasm
COPY ../cpp/+preset-wasm-threads/bin/barretenberg.wasm dest/node-cjs/barretenberg_wasm/barretenberg-threads.wasm

esm:
    RUN yarn build:esm
    SAVE ARTIFACT /usr/src/barretenberg/ts-build build

cjs:
    COPY scripts/cjs_postprocess.sh scripts/
    RUN yarn build:cjs
    SAVE ARTIFACT /usr/src/barretenberg/ts-build build

browser:
    RUN yarn build:browser
    SAVE ARTIFACT /usr/src/barretenberg/ts-build build

test-prettier-format:
    RUN yarn formatting

build:
    # collect all our build types
    COPY +esm/build /usr/src/barretenberg/ts-build
    COPY +cjs/build /usr/src/barretenberg/ts-build
    COPY +browser/build /usr/src/barretenberg/ts-build
    # We want to create a pure package, as would be published to npm, for consuming projects.
    RUN yarn pack && tar zxf package.tgz && rm package.tgz && mv package ../ts
    SAVE ARTIFACT /usr/src/barretenberg/ts build

test:
    BUILD +test-prettier-format
    # We frequently get tests timing out in GA, increase the timeout here
    RUN yarn test --testTimeout=300000
