#!/usr/bin/env bash
# Launches tmux with 1 window that has 2 panes running, from top to bottom:
# - aztec.js
# - a shell in end-to-end. If a test is given as an argument, the test will be run here automatically.
TEST=$1
SESSION_NAME=work

cd $(git rev-parse --show-toplevel)

if tmux has-session -t $SESSION_NAME > /dev/null 2>&1; then
  tmux attach -t $SESSION_NAME
else
  tmux new-session -s $SESSION_NAME -d \
  split-window \;  \
  select-layout even-vertical \; \
  # Give a chance for terminals to start (avoids double command echo).
  sleep 3
  tmux select-pane -t 0 \; \
  send-keys 'cd yarn-project/aztec.js' C-m \; \
  select-pane -t 1 \; \
  send-keys "cd yarn-project/end-to-end && ([ -z \"$TEST\" ] || (yarn test $TEST))" C-m \; \
  attach \;
fi
