#!/bin/bash
# Script for updating tsconfig project references.

if [ $# -eq 0 ]; then
    echo "Usage: $0 path/to/tsconfig.json"
    exit 1
fi

TSCONFIG_FILE="$1"

if [ ! -f "$TSCONFIG_FILE" ]; then
    echo "Error: $TSCONFIG_FILE not found."
    exit 2
fi

TSCONFIG_DIR=$(dirname "$TSCONFIG_FILE")
TS_FILES=$(find "$TSCONFIG_DIR" -type f -name "*.ts" -o -name "*.tsx")
IMPORT_REGEX='^import.*@aztec.([a-zA-Z0-9_\-\.]+)'

REFERENCES="["
for FILE in $TS_FILES; do
    while read -r LINE; do
        if [[ $LINE =~ $IMPORT_REGEX ]]; then
            PACKAGE_NAME="${BASH_REMATCH[1]}"
            REFERENCE="{ \"path\": \"../${PACKAGE_NAME}/tsconfig.dest.json\" },"
            if [[ $REFERENCES != *"${REFERENCE}"* ]]; then
                REFERENCES+=$REFERENCE
            fi
        fi
    done < "$FILE"
done

REFERENCES=${REFERENCES%,}
REFERENCES+="]"

jq --argjson references "$REFERENCES" '.references = $references' "$TSCONFIG_FILE" > "${TSCONFIG_FILE}.tmp" && mv "${TSCONFIG_FILE}.tmp" "$TSCONFIG_FILE"