if(MULTITHREADING)
    message(STATUS "Multithreading is enabled.")
    add_compile_options(-pthread)
    add_link_options(-pthread)
    if(WASM)
        add_compile_options(--target=wasm32-wasi-threads)
        add_link_options(--target=wasm32-wasi-threads)
    endif()
    #add_compile_options(-fsanitize=thread)
    #add_link_options(-fsanitize=thread)
else()
    message(STATUS "Multithreading is disabled.")
    add_definitions(-DNO_MULTITHREADING)
    set(OMP_MULTITHREADING OFF)
endif()

if(OMP_MULTITHREADING)
    find_package(OpenMP REQUIRED)
    message(STATUS "OMP multithreading is enabled.")
    link_libraries(OpenMP::OpenMP_CXX)
else()
    message(STATUS "OMP multithreading is disabled.")
    add_definitions(-DNO_OMP_MULTITHREADING)
endif()

if(DISABLE_TBB)
    message(STATUS "Intel Thread Building Blocks is disabled.")
    add_definitions(-DNO_TBB)
else()
    find_package(TBB QUIET OPTIONAL_COMPONENTS tbb)
    if(${TBB_FOUND})
        message(STATUS "Intel Thread Building Blocks is enabled.")
    else()
        message(STATUS "Could not locate TBB.")
        add_definitions(-DNO_TBB)
    endif()
endif()
