//! Tagged-map serialization format for Noir bytecode.
//!
//! Design: [issue #12554](https://github.com/noir-lang/noir/issues/12554).
//!
//! This crate currently provides:
//! - The [`MsgpackTagged`] trait — metadata-only, exposing each type's wire
//!   shape via [`Tagged`] plus a hook for building a [`TagRegistry`].
//! - [`TagRegistry`] / [`Entry`] — the runtime data structure populated by
//!   recursive [`MsgpackTagged::register_into`] calls and consulted by the
//!   wrapper Serializer/Deserializer (added in a follow-up step).

mod containers;
mod primitives;
mod registry;

pub use msgpack_tagged_derive::MsgpackTagged;
pub use registry::{Entry, Product, Sum, TagRegistry, Tagged, Variant, VariantKind};

/// The integer tag used as a wire-level identifier for struct fields and enum
/// variants. `u8` keeps tags inside msgpack's `fixint` range (0–127) at the
/// 1-byte-per-tag encoding and rejects `#[tag(N)]` annotations with `N > 255`
/// at compile time.
pub type Tag = u8;

/// A type that participates in the tagged-map wire format.
///
/// Implementations are typically generated by `#[derive(MsgpackTagged)]` from the
/// `msgpack_tagged_derive` crate, but can also be hand-written for primitives,
/// container types, or shadow-DTO public types via `#[tagged(via(WireType))]`.
///
/// The trait is metadata-only: it does *not* replace [`serde::Serialize`] /
/// [`serde::Deserialize`]. It sits alongside them and exposes the type's wire
/// shape plus a recursive registry-build hook.
#[diagnostic::on_unimplemented(
    note = "use `#[derive(MsgpackTagged)]` on the type, or `#[tagged(via(WireType))]` on a shadow-DTO public type that delegates to a wire companion",
    note = "for container fields, use `BTreeMap` / `BTreeSet` — `HashMap` / `HashSet` are deliberately unsupported on the wire because their iteration order is non-deterministic"
)]
pub trait MsgpackTagged: 'static {
    /// The wire shape of this type — either a [`Product`] (struct/tuple
    /// struct) or a [`Sum`] (enum). The derive macro emits this from
    /// `#[tag(N)]` annotations; primitives and container types use a
    /// `Tagged::Product` with empty `fields`, signalling they don't appear
    /// directly on the wire as a registry entry but still satisfy the bound.
    const TAGGED: Tagged;

    /// Recursively register this type and every tagged field type into a registry.
    ///
    /// The macro emits the body: it calls `reg.try_insert::<Self>(...)` and, on
    /// first insert, recurses into each generic and tagged-field type via their
    /// own `register_into`. Idempotent — re-registering a type is a no-op.
    fn register_into(reg: &mut TagRegistry);
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Hand-written struct-shaped impl exercising every `Product` field.
    struct Foo;
    impl MsgpackTagged for Foo {
        const TAGGED: Tagged = Tagged::Product(Product {
            fields: &[(0, "a"), (1, "b")],
            reserved: &[3],
            defaults: &[],
            allow_unknown_tags: true,
        });
        fn register_into(_reg: &mut TagRegistry) {}
    }

    /// Minimal impl supplying a `TAGGED` with all `Product` extras blank —
    /// proves the empty-defaults shape compiles and reads back as expected.
    struct Bar;
    impl MsgpackTagged for Bar {
        const TAGGED: Tagged = Tagged::Product(Product {
            fields: &[],
            reserved: &[],
            defaults: &[],
            allow_unknown_tags: false,
        });
        fn register_into(_reg: &mut TagRegistry) {}
    }

    #[test]
    #[allow(clippy::assertions_on_constants)]
    fn bar_disallows_unknown_by_default() {
        let p = <Bar as MsgpackTagged>::TAGGED.as_product().unwrap();
        assert!(!p.allow_unknown_tags);
    }

    #[test]
    #[allow(clippy::const_is_empty)]
    fn bar_has_nothing_reserved_or_defaulted() {
        let p = <Bar as MsgpackTagged>::TAGGED.as_product().unwrap();
        assert!(p.reserved.is_empty());
        assert!(p.defaults.is_empty());
    }

    #[test]
    fn foo_constants_match_what_was_written() {
        let p = <Foo as MsgpackTagged>::TAGGED.as_product().unwrap();
        assert_eq!(p.fields, &[(0, "a"), (1, "b")]);
        assert_eq!(p.reserved, &[3]);
        assert!(p.allow_unknown_tags);
    }
}
