//! Tagged-map serialization format for Noir bytecode.
//!
//! Design: [issue #12554](https://github.com/noir-lang/noir/issues/12554).
//!
//! This crate currently provides:
//! - The [`MsgpackTagged`] trait — metadata-only, exposing each type's wire
//!   shape via [`Tagged`] plus a hook for building a [`TagRegistry`].
//! - [`TagRegistry`] / [`Entry`] — the runtime data structure populated by
//!   recursive [`MsgpackTagged::register_into`] calls and consulted by the
//!   wrapper Serializer/Deserializer (added in a follow-up step).

// `msgpack_tagged_derive`'s `MsgpackTagged` proc-macro emits
// `::msgpack_tagged::...` paths to remain hygienic at every call site. From
// inside this crate that absolute path doesn't resolve unless we tell rustc
// the current crate also goes by that name.
extern crate self as msgpack_tagged;

mod containers;
mod primitives;
mod registry;

pub mod deserializer;
pub mod serializer;

pub use deserializer::{Deserializer, msgpack_tagged_deserialize};
pub use serializer::{Serializer, msgpack_tagged_serialize};

pub use msgpack_tagged_derive::MsgpackTagged;
pub use registry::{
    Entry, Product, Sum, TagRegistry, Tagged, Variant, VariantKind, type_name_basename,
};

/// On-wire shape for product types (structs, tuple structs, enum-variant
/// payloads). Picked per-type on the [`Serializer`] (see
/// [`Serializer::new`] / [`Serializer::with_strategy`]). Enum variants
/// are *always* int-keyed under `MsgpackTagged` regardless of strategy —
/// the strategy only affects struct shape.
///
/// * [`EncodingStrategy::Tagged`] (default) — int-keyed `fixmap`
///   `{0: a, 1: b, …}`. Schema-evolution friendly: identification is by
///   tag, so fields can be added, removed (via `#[tagged(reserved(...))]`),
///   or reordered freely. Costs one byte per field for the tag.
/// * [`EncodingStrategy::Array`] — positional `fixarray` `[a, b, …]`,
///   fields emitted in tag-ascending order. Minimum overhead. Identification
///   is by position, so evolvability is limited to *trailing* changes:
///   - **Adding a trailing field** is backward-compat when the field is
///     marked `#[serde(default)]` — V1 wire (shorter) decodes into V2
///     type, the default fills the new position.
///   - **Removing a trailing field** is forward-compat when the type
///     opts into `#[tagged(allow_unknown_tags)]` — V2 wire (longer)
///     decodes into V1 type, the extra trailing position is ignored.
///   - Anything else (middle insert/remove, reorder, type change) is
///     wire-breaking. Pick this strategy for small leaf types where size
///     wins over flexibility and the type is unlikely to need
///     middle-of-shape edits.
///
/// **Auto-downgrade to Tagged.** If a type has `#[tagged(reserved(N))]`
/// where `N` falls *between* (or before) the active tags, requesting
/// `Array` for it would corrupt round-trips: V2's positional wire only
/// carries active values, but the decoder walks a merged-sorted layout
/// of `(active + reserved)` tags and would drain a wire byte at the
/// reserved slot intended for a later active field. The encoder detects
/// this and silently switches to `Tagged` for that product only — other
/// types in the same serializer keep their configured strategy.
/// Strictly-trailing reserved tags (every reserved tag greater than
/// every active tag) keep `Array`: the decoder hits `wire_remaining == 0`
/// before reaching the trailing reserved slot, so positional alignment
/// holds. The migration guide in the crate README walks through both
/// cases with examples.
///
/// The decoder probes the wire shape (`fixmap` vs. `fixarray`) per struct
/// at decode time, so a single buffer can mix both strategies across
/// nested types freely.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum EncodingStrategy {
    /// Int-keyed map. Default — most backward/forward compatible.
    #[default]
    Tagged,
    /// Positional array. Smaller; not schema-evolvable.
    Array,
}

/// The integer tag used as a wire-level identifier for struct fields and enum
/// variants. `u8` keeps tags inside msgpack's `fixint` range (0–127) at the
/// 1-byte-per-tag encoding and rejects `#[tag(N)]` annotations with `N > 255`
/// at compile time.
pub type Tag = u8;

/// A type that participates in the tagged-map wire format.
///
/// Implementations are typically generated by `#[derive(MsgpackTagged)]` from the
/// `msgpack_tagged_derive` crate, but can also be hand-written for primitives,
/// container types, or shadow-DTO public types via `#[tagged(via(WireType))]`.
///
/// The trait is metadata-only: it does *not* replace [`serde::Serialize`] /
/// [`serde::Deserialize`]. It sits alongside them and exposes the type's wire
/// shape plus a recursive registry-build hook.
#[diagnostic::on_unimplemented(
    note = "use `#[derive(MsgpackTagged)]` on the type, or `#[tagged(via(WireType))]` on a shadow-DTO public type that delegates to a wire companion",
    note = "for container fields, use `BTreeMap` / `BTreeSet` — `HashMap` / `HashSet` are deliberately unsupported on the wire because their iteration order is non-deterministic"
)]
pub trait MsgpackTagged: 'static {
    /// The wire shape of this type — either a [`Product`] (struct/tuple
    /// struct) or a [`Sum`] (enum). The derive macro emits this from
    /// `#[tag(N)]` annotations; primitives and container types use a
    /// `Tagged::Product` with empty `fields`, signalling they don't appear
    /// directly on the wire as a registry entry but still satisfy the bound.
    const TAGGED: Tagged;

    /// Recursively register this type and every tagged field type into a registry.
    ///
    /// The macro emits the body: it calls `reg.try_insert::<Self>(...)` and, on
    /// first insert, recurses into each generic and tagged-field type via their
    /// own `register_into`. Idempotent — re-registering a type is a no-op.
    fn register_into(reg: &mut TagRegistry);
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Hand-written struct-shaped impl exercising every `Product` field.
    struct Foo;
    impl MsgpackTagged for Foo {
        const TAGGED: Tagged = Tagged::Product(Product {
            fields: &[(0, "a"), (1, "b")],
            reserved: &[3],
            allow_unknown_tags: true,
            tag_order_matches_source: true,
        });
        fn register_into(_reg: &mut TagRegistry) {}
    }

    /// Minimal impl supplying a `TAGGED` with `Product` extras blank —
    /// proves the empty shape compiles and reads back as expected.
    struct Bar;
    impl MsgpackTagged for Bar {
        const TAGGED: Tagged = Tagged::empty_product();
        fn register_into(_reg: &mut TagRegistry) {}
    }

    #[test]
    #[allow(clippy::assertions_on_constants)]
    fn bar_disallows_unknown_by_default() {
        let p = <Bar as MsgpackTagged>::TAGGED.as_product().unwrap();
        assert!(!p.allow_unknown_tags);
    }

    #[test]
    #[allow(clippy::const_is_empty)]
    fn bar_has_nothing_reserved() {
        let p = <Bar as MsgpackTagged>::TAGGED.as_product().unwrap();
        assert!(p.reserved.is_empty());
    }

    #[test]
    fn foo_constants_match_what_was_written() {
        let p = <Foo as MsgpackTagged>::TAGGED.as_product().unwrap();
        assert_eq!(p.fields, &[(0, "a"), (1, "b")]);
        assert_eq!(p.reserved, &[3]);
        assert!(p.allow_unknown_tags);
    }
}
