//! Tagged-map serialization format for Noir bytecode.
//!
//! Design: [issue #12554](https://github.com/noir-lang/noir/issues/12554).
//!
//! This crate currently provides:
//! - The [`MsgpackTagged`] trait — metadata-only, exposing per-type tag information
//!   plus a hook for building a [`TagRegistry`].
//! - A stub [`TagRegistry`] (will be fleshed out alongside the wrapper Serializer
//!   in a follow-up step).
//!
//! Future steps will add: blanket impls for primitives and standard containers,
//! the `TaggedMsgpackSerializer`/`TaggedMsgpackDeserializer` wrappers, and the
//! companion `msgpack_tagged_derive` crate that emits this trait.

/// A type that participates in the tagged-map wire format.
///
/// Implementations are typically generated by `#[derive(MsgpackTagged)]` from the
/// `msgpack_tagged_derive` crate, but can also be hand-written for primitives,
/// container types, or shadow-DTO public types via `#[via(WireType)]`.
///
/// The trait is metadata-only: it does *not* replace [`serde::Serialize`] /
/// [`serde::Deserialize`]. It sits alongside them and exposes per-type tag
/// information plus a recursive registry-build hook.
pub trait MsgpackTagged {
    /// Tag-to-field-name table for this type, written by the macro from `#[tag(N)]`
    /// attributes in tag order. Empty for newtypes and shadow-DTO public types
    /// using `#[via(...)]`.
    const TAGS: &'static [(u8, &'static str)];

    /// Tags that have been retired via `#[reserved(...)]` on the type. These tags
    /// must never be reused for a different field meaning — the macro enforces
    /// this at compile time, and the decoder skips values keyed by reserved tags
    /// silently (assuming they're remnants from an older schema).
    const RESERVED: &'static [u8] = &[];

    /// Whether unknown tags encountered on decode should be ignored (`true`) or
    /// treated as a decode error (`false`).
    ///
    /// Default `false` is the strict policy — an unknown tag signals version skew
    /// or a semantic change the local schema doesn't understand. Opt into lenient
    /// behavior with `#[allow_unknown_tags]` on the type, typically reserved for
    /// metadata-bearing top-level types like `Program` and `Circuit`.
    const ALLOW_UNKNOWN_TAGS: bool = false;

    /// Recursively register this type and every tagged field type into a registry.
    ///
    /// The macro emits the body: it calls `reg.try_insert::<Self>(...)` and, on
    /// first insert, recurses into each generic and tagged-field type via their
    /// own `register_into`. Idempotent — re-registering a type is a no-op.
    fn register_into(reg: &mut TagRegistry);
}

/// A registry of types participating in tagged-map serialization.
///
/// Built once per encode/decode call by walking the type graph from a top-level
/// type via [`MsgpackTagged::register_into`]. The wrapper Serializer/Deserializer
/// consults the registry at `serialize_struct` / `deserialize_struct` time to
/// translate between serde field names and integer tags.
///
/// Stub: implementation deferred to a follow-up step alongside the wrapper.
#[derive(Default)]
pub struct TagRegistry {
    _placeholder: (),
}

impl TagRegistry {
    /// Construct an empty registry.
    pub fn new() -> Self {
        Self::default()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Hand-written impl that exercises every const on the trait. Real types
    /// will get equivalent impls from the proc-macro.
    struct Foo;

    impl MsgpackTagged for Foo {
        const TAGS: &'static [(u8, &'static str)] = &[(0, "a"), (1, "b")];
        const RESERVED: &'static [u8] = &[3];
        const ALLOW_UNKNOWN_TAGS: bool = true;

        fn register_into(_reg: &mut TagRegistry) {}
    }

    /// Minimal impl that supplies only `TAGS` and `register_into`, leaving
    /// `RESERVED` and `ALLOW_UNKNOWN_TAGS` at their defaults. This impl
    /// compiling is itself the proof that the defaults are in place.
    struct Bar;

    impl MsgpackTagged for Bar {
        const TAGS: &'static [(u8, &'static str)] = &[];

        fn register_into(_reg: &mut TagRegistry) {}
    }

    #[test]
    fn disallows_unknown_by_default() {
        assert!(!<Bar as MsgpackTagged>::ALLOW_UNKNOWN_TAGS);
    }

    #[test]
    fn nothing_reserved_by_default() {
        assert!(<Bar as MsgpackTagged>::RESERVED.is_empty());
    }

    #[test]
    fn impl_constants_match_what_was_written() {
        assert_eq!(Foo::TAGS, &[(0, "a"), (1, "b")]);
        assert_eq!(Foo::RESERVED, &[3]);
    }

    #[test]
    fn register_into_compiles_against_stub_registry() {
        let mut reg = TagRegistry::new();
        Foo::register_into(&mut reg);
        Bar::register_into(&mut reg);
    }
}
