FROM aztecprotocol/crosstool-ng-arm64:latest
WORKDIR /usr/src/barretenberg
COPY . .
RUN mkdir build && cd build && cmake -DTOOLCHAIN=arm64-linux-gcc .. && make -j$(nproc)
RUN cd build && qemu-aarch64 ./test/barretenberg_tests
ENTRYPOINT /bin/bash