# Unused & not maintained. This probably won't work without changes.

FROM aztecprotocol/crosstool-ng-arm64:latest
WORKDIR /usr/src/barretenberg/cpp
COPY . .
RUN cmake --toolchain ./cmake/toolchains/aarch64-linux.cmake --preset gcc && cmake --build --preset gcc
RUN cd build && qemu-aarch64 ./test/barretenberg_tests
ENTRYPOINT /bin/bash