# The build context for docs is the root of the repository.
# Be very specific about what we include.
*

!docs
docs/node_modules
!l1-contracts/src
!l1-contracts/test
!barretenberg/cpp/src/barretenberg
!.release-please-manifest.json
!boxes

# Docs build fetches code snippets from the last release using git show.
!.git