name: Download Nargo with --no-default-features
description: Downloads the nargo-no-default-features binary from an artifact and adds it to the path

runs:
  using: composite
  steps:
    - name: Download nargo binary
      uses: actions/download-artifact@v4
      with:
        name: nargo
        path: ./nargo-no-default-features

    - name: Set nargo on PATH
      shell: bash
      run: |
        nargo_binary="${{ github.workspace }}/nargo-no-default-features/nargo"
        chmod +x $nargo_binary
        echo "$(dirname $nargo_binary)" >> $GITHUB_PATH
