#!/usr/bin/env bash
set -xe

$(aws ecr get-login --region us-east-2 --no-include-email) 2> /dev/null

REPOSITORY=bb.js
IMAGE_URI=$($(git rev-parse --show-toplevel)/build-system/scripts/calculate_image_uri $REPOSITORY)
docker run --rm $IMAGE_URI
