VERSION 0.8

E2E_COMPOSE_TEST:
  FUNCTION
  ARG test
  ARG compose_file=./scripts/docker-compose.yml
  ARG debug="aztec:*"
  ARG EARTHLY_TARGET_NAME
  LOCALLY
  ENV TEST=$test
  ENV DEBUG=$debug
  LET project_name=$(echo $test | sed 's/\./_/g')
  IF docker compose > /dev/null 2>&1
    LET CMD="docker compose"
  ELSE
    LET CMD="docker-compose"
  END
  WITH DOCKER \
    --load aztecprotocol/aztec:latest=../+aztec \
    --load aztecprotocol/end-to-end:latest=../+end-to-end \
    --load aztecprotocol/foundry-nightly-de33b6af53005037b463318d2628b5cfcaf3991:latest=../../build-images+build
    # Run our docker compose, ending whenever sandbox ends, filtering out noisy eth_getLogs
    RUN $CMD -p $project_name -f $compose_file up --exit-code-from=end-to-end --force-recreate
  END

UPLOAD_LOGS:
  FUNCTION
  ARG PULL_REQUEST
  ARG BRANCH
  ARG COMMIT_HASH
  LOCALLY
  LET COMMIT_HASH="${COMMIT_HASH:-$(git rev-parse HEAD)}"
  FROM ../../+scripts
  COPY ./log /usr/var/log
  ENV PULL_REQUEST=$PULL_REQUEST
  ENV BRANCH=$BRANCH
  ENV COMMIT_HASH=$COMMIT_HASH
  RUN --secret AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY /usr/src/scripts/logs/upload_logs_to_s3.sh /usr/var/log

# Define e2e tests
e2e-tests:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e

flakey-e2e-tests:
  FROM ../+end-to-end
  RUN yarn test --passWithNoTests ./src/flakey || true

e2e-sandbox-example:
  DO +E2E_COMPOSE_TEST --test=e2e_sandbox_example.test.ts

uniswap-trade-on-l1-from-l2:
  DO +E2E_COMPOSE_TEST --test=uniswap_trade_on_l1_from_l2.test.ts

integration-l1-publisher:
  DO +E2E_COMPOSE_TEST --test=integration_l1_publisher.test.ts

e2e-browser:
  DO +E2E_COMPOSE_TEST --test=e2e_aztec_js_browser.test.ts

pxe:
  DO +E2E_COMPOSE_TEST --test=pxe.test.ts

e2e-docs-examples:
  DO +E2E_COMPOSE_TEST --test=docs_examples.test.ts

guides-writing-an-account-contract:
  DO +E2E_COMPOSE_TEST --test=guides/writing_an_account_contract.test.ts

guides-dapp-testing:
  DO +E2E_COMPOSE_TEST --test=guides/dapp_testing.test.ts

# TODO intermittent failure
# guides-sample-dapp:
#   DO +E2E_COMPOSE_TEST --test=sample-dapp

# TODO currently hangs for hour+
# guides-up-quick-start:
#   DO +E2E_COMPOSE_TEST --test=guides/up_quick_start.test.ts

bench-publish-rollup:
  ARG PULL_REQUEST
  ARG BRANCH
  ARG COMMIT_HASH
  DO +E2E_COMPOSE_TEST --test=benchmarks/bench_publish_rollup.test.ts --debug="aztec:benchmarks:*,aztec:sequencer,aztec:sequencer:*,aztec:world_state,aztec:merkle_trees" --compose_file=./scripts/docker-compose-no-sandbox.yml
  DO +UPLOAD_LOGS --e2e_mode=$e2e_mode --PULL_REQUEST=$PULL_REQUEST --BRANCH=$BRANCH --COMMIT_HASH=$COMMIT_HASH

bench-process-history:
  ARG PULL_REQUEST
  ARG BRANCH
  ARG COMMIT_HASH
  DO +E2E_COMPOSE_TEST --test=benchmarks/bench_process_history.test.ts --debug="aztec:benchmarks:*,aztec:sequencer,aztec:sequencer:*,aztec:world_state,aztec:merkle_trees" --compose_file=./scripts/docker-compose-no-sandbox.yml
  DO +UPLOAD_LOGS --e2e_mode=$e2e_mode --PULL_REQUEST=$PULL_REQUEST --BRANCH=$BRANCH --COMMIT_HASH=$COMMIT_HASH

bench-tx-size:
  ARG PULL_REQUEST
  ARG BRANCH
  ARG COMMIT_HASH
  DO +E2E_COMPOSE_TEST --test=benchmarks/bench_tx_size_fees.test.ts --debug="aztec:benchmarks:*,aztec:sequencer,aztec:sequencer:*,aztec:world_state,aztec:merkle_trees" --enable_gas=1 --compose_file=./scripts/docker-compose-no-sandbox.yml
  DO +UPLOAD_LOGS --e2e_mode=$e2e_mode --PULL_REQUEST=$PULL_REQUEST --BRANCH=$BRANCH --COMMIT_HASH=$COMMIT_HASH
