VERSION 0.8
ARG --global skip_build=false

E2E_COMPOSE_TEST:
  FUNCTION
  ARG test
  ARG compose_file=./scripts/docker-compose.yml
  ARG debug="aztec:*"
  LOCALLY
  ENV TEST=$test
  ENV DEBUG=$debug
  LET project_name=$(echo $test | sed 's/\./_/g')
  IF docker compose > /dev/null 2>&1
    LET CMD="docker compose"
  ELSE
    LET CMD="docker-compose"
  END
  # In CI, we do an optimization to push these images to docker once
  # We still want the default code path to work with no faff locally
  # To not rebuild unnecessarily, we pass --skip_build=true in CI
  IF [ $skip_build != "true" ]
    WAIT
      BUILD ../+export-e2e-test-images
    END
  END
  # Let docker compose know about the pushed tags above
  ENV AZTEC_DOCKER_TAG=$(git rev-parse HEAD)
  # Run our docker compose, ending whenever sandbox ends, filtering out noisy eth_getLogs
  RUN $CMD -p $project_name -f $compose_file up --exit-code-from=end-to-end --force-recreate

UPLOAD_LOGS:
  FUNCTION
  ARG PULL_REQUEST
  ARG BRANCH
  ARG COMMIT_HASH
  LOCALLY
  LET COMMIT_HASH="${COMMIT_HASH:-$(git rev-parse HEAD)}"
  FROM ../../+scripts
  COPY ./log /usr/var/log
  ENV PULL_REQUEST=$PULL_REQUEST
  ENV BRANCH=$BRANCH
  ENV COMMIT_HASH=$COMMIT_HASH
  RUN --secret AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY /usr/src/scripts/logs/upload_logs_to_s3.sh /usr/var/log

e2e_2_pxes:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_2_pxes.test.ts

e2e_account_contracts:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_account_contracts.test.ts

e2e_auth_contract:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_auth_contract.test.ts

e2e_authwit:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_authwit.test.ts

e2e_avm_simulator:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_avm_simulator.test.ts

e2e_blacklist_token_contract:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_blacklist_token_contract

e2e_block_building:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_block_building.test.ts

e2e_card_game:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_card_game.test.ts

e2e_cheat_codes:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_cheat_codes.test.ts

e2e_counter_contract:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_counter_contract.test.ts

e2e_cross_chain_messaging:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_cross_chain_messaging.test.ts

e2e_crowdfunding_and_claim:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_crowdfunding_and_claim.test.ts

e2e_dapp_subscription:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_dapp_subscription.test.ts

e2e_delegate_calls:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_delegate_calls

e2e_deploy_contract:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_deploy_contract

e2e_encryption:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_encryption.test.ts

e2e_escrow_contract:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_escrow_contract.test.ts

e2e_fees:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_fees.test.ts

e2e_key_registry:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_key_registry.test.ts

e2e_lending_contract:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_lending_contract.test.ts

e2e_max_block_number:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_max_block_number.test.ts

e2e_multiple_accounts_1_enc_key:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_multiple_accounts_1_enc_key.test.ts

e2e_nested_contract:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_nested_contract

e2e_non_contract_account:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_non_contract_account.test.ts

e2e_note_getter:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_note_getter.test.ts

e2e_ordering:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_ordering.test.ts

e2e_outbox:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_outbox.test.ts

e2e_pending_note_hashes_contract:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_pending_note_hashes_contract.test.ts

e2e_private_voting_contract:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_private_voting_contract.test.ts

e2e_public_cross_chain_messaging:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_public_cross_chain_messaging

e2e_public_to_private_messaging:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_public_to_private_messaging.test.ts

e2e_state_vars:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_state_vars.test.ts

e2e_static_calls:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_static_calls.test.ts

e2e_token_contract:
  FROM ../+end-to-end
  RUN yarn test ./src/e2e_token_contract

flakey-e2e-tests:
  FROM ../+end-to-end
  RUN yarn test --passWithNoTests ./src/flakey || true

e2e-sandbox-example:
  DO +E2E_COMPOSE_TEST --test=e2e_sandbox_example.test.ts

uniswap-trade-on-l1-from-l2:
  DO +E2E_COMPOSE_TEST --test=uniswap_trade_on_l1_from_l2.test.ts

integration-l1-publisher:
  DO +E2E_COMPOSE_TEST --test=integration_l1_publisher.test.ts

e2e-browser:
  DO +E2E_COMPOSE_TEST --test=e2e_aztec_js_browser.test.ts

pxe:
  DO +E2E_COMPOSE_TEST --test=pxe.test.ts

e2e-docs-examples:
  DO +E2E_COMPOSE_TEST --test=docs_examples.test.ts

guides-writing-an-account-contract:
  DO +E2E_COMPOSE_TEST --test=guides/writing_an_account_contract.test.ts

guides-dapp-testing:
  DO +E2E_COMPOSE_TEST --test=guides/dapp_testing.test.ts

# TODO intermittent failure
# guides-sample-dapp:
#   DO +E2E_COMPOSE_TEST --test=sample-dapp

# TODO currently hangs for hour+
# guides-up-quick-start:
#   DO +E2E_COMPOSE_TEST --test=guides/up_quick_start.test.ts

bench-publish-rollup:
  ARG PULL_REQUEST
  ARG BRANCH
  ARG COMMIT_HASH
  DO +E2E_COMPOSE_TEST --test=benchmarks/bench_publish_rollup.test.ts --debug="aztec:benchmarks:*,aztec:sequencer,aztec:sequencer:*,aztec:world_state,aztec:merkle_trees" --compose_file=./scripts/docker-compose-no-sandbox.yml
  DO +UPLOAD_LOGS --e2e_mode=$e2e_mode --PULL_REQUEST=$PULL_REQUEST --BRANCH=$BRANCH --COMMIT_HASH=$COMMIT_HASH

bench-process-history:
  ARG PULL_REQUEST
  ARG BRANCH
  ARG COMMIT_HASH
  DO +E2E_COMPOSE_TEST --test=benchmarks/bench_process_history.test.ts --debug="aztec:benchmarks:*,aztec:sequencer,aztec:sequencer:*,aztec:world_state,aztec:merkle_trees" --compose_file=./scripts/docker-compose-no-sandbox.yml
  DO +UPLOAD_LOGS --e2e_mode=$e2e_mode --PULL_REQUEST=$PULL_REQUEST --BRANCH=$BRANCH --COMMIT_HASH=$COMMIT_HASH

bench-tx-size:
  ARG PULL_REQUEST
  ARG BRANCH
  ARG COMMIT_HASH
  DO +E2E_COMPOSE_TEST --test=benchmarks/bench_tx_size_fees.test.ts --debug="aztec:benchmarks:*,aztec:sequencer,aztec:sequencer:*,aztec:world_state,aztec:merkle_trees" --enable_gas=1 --compose_file=./scripts/docker-compose-no-sandbox.yml
  DO +UPLOAD_LOGS --e2e_mode=$e2e_mode --PULL_REQUEST=$PULL_REQUEST --BRANCH=$BRANCH --COMMIT_HASH=$COMMIT_HASH

bench-proving:
  ARG e2e_mode=local
  ARG PULL_REQUEST
  ARG BRANCH
  ARG COMMIT_HASH
  DO +E2E_COMPOSE_TEST --test=bench_proving --debug="aztec:benchmarks:*,aztec:prover*,aztec:bb*" --e2e_mode=$e2e_mode --enable_gas=1 --compose_file=./scripts/docker-compose-no-sandbox.yml
  DO +UPLOAD_LOGS --e2e_mode=$e2e_mode --PULL_REQUEST=$PULL_REQUEST --BRANCH=$BRANCH --COMMIT_HASH=$COMMIT_HASH
