// PTY-based tests require Unix; expectrl's spawn uses /bin/sh which is unavailable on Windows.
#[cfg(all(test, unix))]
mod tests {
    use std::collections::VecDeque;

    // Some of these imports are consumed by the injected tests
    #[allow(deprecated)]
    use assert_cmd::cargo::cargo_bin;

    use expectrl::{session::Session, spawn};

    // include tests generated by `build.rs`
    include!(concat!(env!("OUT_DIR"), "/debug.rs"));

    fn debugger_execution_success(test_program_dir: &str) {
        #[allow(deprecated)]
        let nargo_bin =
            cargo_bin("nargo").into_os_string().into_string().expect("Cannot parse nargo path");

        let mut dbg_session = start_debug_session(&format!(
            "{nargo_bin} debug --program-dir {test_program_dir} --force-brillig"
        ));

        // send continue which should run to the program to end
        // given we haven't set any breakpoints.
        send_continue_and_check_no_panic(&mut dbg_session);

        send_quit(&mut dbg_session);
        dbg_session
            .expect(expectrl::Regex(".*Circuit witness successfully solved.*"))
            .expect("Expected circuit witness to be successfully solved.");
    }

    fn debugger_test_success(test_program_dir: &str, test_name: &str) {
        #[allow(deprecated)]
        let nargo_bin =
            cargo_bin("nargo").into_os_string().into_string().expect("Cannot parse nargo path");

        let mut dbg_session = start_debug_session(
            &(format!(
                "{nargo_bin} debug --program-dir {test_program_dir} --test-name {test_name} --force-brillig"
            )),
        );

        // send continue which should run to the program to end
        // given we haven't set any breakpoints.
        send_continue_and_check_no_panic(&mut dbg_session);

        send_quit(&mut dbg_session);
        dbg_session
            .expect(expectrl::Regex(".*Testing .*\\.\\.\\. .*ok.*"))
            .expect("Expected test to be successful");
    }

    fn start_debug_session(command: &str) -> Session {
        let mut dbg_session = spawn(command).expect("Could not start debugger session");

        // Start debugger and test that it loads for the given program.
        dbg_session
            .expect(expectrl::Regex(".*\\Starting debugger.*"))
            .expect("Could not start debugger");
        dbg_session
    }

    fn send_quit(dbg_session: &mut Session) {
        // Run the "quit" command, then check that the debugger confirms
        // having successfully solved the circuit witness.
        dbg_session.send_line("quit").expect("Failed to quit debugger");
    }

    /// Exit the session.
    fn exit(mut _dbg_session: Session) {
        // With expectrl and direct spawning of nargo, we don't need to exit bash.
        // The session will drop and close.
    }

    /// While running the debugger, issue a "continue" cmd,
    /// which should run to the program to end or the next breakpoint
    /// ">" is the debugger's prompt, so finding one
    /// after running "continue" indicates that the
    /// debugger has not panicked.
    fn send_continue_and_check_no_panic(dbg_session: &mut Session) {
        dbg_session
            .send_line("c")
            .expect("Debugger panicked while attempting to step through program.");
        dbg_session
            .expect(">")
            .expect("Failed while waiting for debugger to step through program.");
    }

    #[test]
    fn debugger_expected_call_stack() {
        #[allow(deprecated)]
        let nargo_bin =
            cargo_bin("nargo").into_os_string().into_string().expect("Cannot parse nargo path");

        let test_program_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../test_programs/execution_success/regression_7195")
            .canonicalize()
            .unwrap();
        let test_program_dir = test_program_path.display();

        // Start debugger and test that it loads for the given program.
        let mut dbg_session = spawn(&format!(
            "{nargo_bin} debug --raw-source-printing true --program-dir {test_program_dir} --force-brillig"
        ))
        .expect("Could not start debugger session");

        dbg_session
            .expect(expectrl::Regex(".*\\Starting debugger.*"))
            .expect("Could not start debugger");

        let expected_lines_by_command: Vec<VecDeque<&str>> = vec![
            VecDeque::from(["fn main(x: Field, y: pub Field) {"]),
            VecDeque::from(["fn main(x: Field, y: pub Field) {"]),
            VecDeque::from(["fn main(x: Field, y: pub Field) {"]),
            VecDeque::from([
                "let x = unsafe { baz(x) };",
                "unconstrained fn baz(x: Field) -> Field {",
            ]),
            VecDeque::from([
                "let x = unsafe { baz(x) };",
                "unconstrained fn baz(x: Field) -> Field {",
            ]),
            VecDeque::from(["let x = unsafe { baz(x) };", "}"]),
            VecDeque::from(["let x = unsafe { baz(x) };"]),
            VecDeque::from(["foo(x);", "fn foo(x: Field) {"]),
            VecDeque::from(["foo(x);", "fn foo(x: Field) {"]),
            VecDeque::from([
                "foo(x);",
                "let y = unsafe { baz(x) };",
                "unconstrained fn baz(x: Field) -> Field {",
            ]),
            VecDeque::from([
                "foo(x);",
                "let y = unsafe { baz(x) };",
                "unconstrained fn baz(x: Field) -> Field {",
            ]),
            VecDeque::from(["foo(x);", "let y = unsafe { baz(x) };", "}"]),
            VecDeque::from(["foo(x);", "let y = unsafe { baz(x) };"]),
            VecDeque::from(["foo(x);", "bar(y);", "fn bar(y: Field) {"]),
            VecDeque::from(["foo(x);", "bar(y);", "fn bar(y: Field) {"]),
            VecDeque::from(["foo(x);", "bar(y);", "assert(y != 0);"]),
        ];

        // Try to use relative paths if possible, otherwise the test breaks when run from the repository root
        let at_filename = std::env::current_dir()
            .ok()
            .and_then(|dir| test_program_path.strip_prefix(&dir).ok())
            .map_or_else(
                || format!("At {test_program_dir}"),
                |stripped| format!("At {}", stripped.display()),
            );

        for mut expected_lines in expected_lines_by_command {
            // While running the debugger, issue a "next" cmd,
            // which should run to the program to the next source line given
            // we haven't set any breakpoints.
            // ">" is the debugger's prompt, so finding one
            // after running "next" indicates that the
            // debugger has not panicked for this step.
            dbg_session
                .send_line("next")
                .expect("Debugger panicked while attempting to step through program.");
            dbg_session
                .expect(">")
                .expect("Failed while waiting for debugger to step through program.");

            while let Some(expected_line) = expected_lines.pop_front() {
                let line = loop {
                    // Let's use expectrl's session.expect(Regex(".*\\n")) to simulate read_line.
                    let found =
                        dbg_session.expect(expectrl::Regex(".+\\n")).expect("Failed to read line");
                    let read_line = String::from_utf8_lossy(found.get(0).unwrap()).to_string();

                    if !(read_line.contains("> next")
                        || read_line.contains("At opcode")
                        || read_line.contains(at_filename.as_str())
                        || read_line.contains("..."))
                    {
                        break read_line;
                    }
                };
                let ascii_line: String = line.chars().filter(char::is_ascii).collect();
                let line_expected_to_contain = expected_line.trim();
                assert!(
                    ascii_line.contains(line_expected_to_contain),
                    "{ascii_line:?}\ndid not contain\n{line_expected_to_contain:?}",
                );
            }
        }

        // Run the "quit" command
        dbg_session.send_line("quit").expect("Failed to quit debugger");
    }
}
