name: Publish documentation

on:
  push:
    branches:
      - master
    paths: [docs/**]
  workflow_dispatch:

permissions: {}

jobs:
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout release branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: '22.15.0'
          cache: 'yarn'
          cache-dependency-path: 'docs/yarn.lock'

      - name: Install docs dependencies
        working-directory: docs
        run: yarn install --immutable

      - name: Query active docs versions
        working-directory: docs
        run: yarn version::stables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docs for deploying
        working-directory: docs
        run: yarn build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@d22a32a27c918fe470bbc562e984f80ec48c2668 # v4.0.0
        with:
          publish-dir: "./docs/build"
          production-branch: master
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-github-deployment: false
          deploy-message: "Deploy from GitHub Actions for tag ${{ inputs.noir-ref }}"
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
