name: Publish rustdoc

on:
  push:
    branches:
      - master

permissions: {}

# This will cancel previous runs when a branch or PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: taiki-e/install-action@just

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@1.89.0

      - name: Configure cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v6

      - name: Clean docs folder
        run: cargo clean --doc

      - name: Build docs
        run: just doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add redirect
        run: echo '<meta http-equiv="refresh" content="0;url=nargo/index.html">' > target/doc/index.html

      - name: Remove lock file
        run: rm target/doc/.lock

      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: rustdoc
          path: target/doc

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: gh-pages

      - name: Clear old docs
        run: rm -rf ./docs

      - name: Download rustdoc output
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: rustdoc
          path: ./docs

      - name: Configure git
        run: |
          git config --global user.name "rustdoc"
          git config --global user.email "github@users.noreply.github.com"

      - name: Commit new docs
        run: |
          # This could _potentially_ clash with pushing benchmarks to this branch at the same time.
          # In practice, this will complete much sooner than the benchmarks are generated.
          git add ./docs/*
          git commit -m "update rustdoc"
          git push
