name: Windows Test

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master
      - main


permissions:
  contents: read

# This will cancel previous runs when a branch or PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests-windows:
    name: Run tests (Windows)
    runs-on: windows-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@1.89.0

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          save-if: ${{ github.event_name != 'merge_group' }}

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.88

      - name: Run tests
        run: |
          $env:RUST_MIN_STACK = "8388608"
          cargo nextest run --workspace
        shell: powershell
